// routing.proto — shared routing composition types.
//
// RoutingOverride maps a client-facing model ID to a routing tree.
// A routing tree is a recursive structure of target, chain, or split nodes:
//   target — single hop to a named provider + optional backend model
//   chain  — ordered fallback; tries children in order, stops at first success
//   split  — weighted traffic distribution; one child chosen per request
//
// Nesting rules:
//   chain children may be target or split
//   split children may be target or chain
//   nested split-inside-split is not supported
//
// These types are imported by config/admin/v1 (snapshot-level overrides)
// and key/admin/v1 (per-key routing overrides stored on the Key entity).
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/routing/v1/routing.proto

package routingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoutingOverride maps a client-facing model ID to a routing tree.
type RoutingOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // client-facing model ID (e.g. "claude-haiku-4-5")
	Node          *RoutingNode           `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingOverride) Reset() {
	*x = RoutingOverride{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingOverride) ProtoMessage() {}

func (x *RoutingOverride) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingOverride.ProtoReflect.Descriptor instead.
func (*RoutingOverride) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingOverride) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RoutingOverride) GetNode() *RoutingNode {
	if x != nil {
		return x.Node
	}
	return nil
}

// RoutingNode is a recursive routing tree. Exactly one of target, chain, or
// split must be set.
type RoutingNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RoutingNode_Target
	//	*RoutingNode_Chain
	//	*RoutingNode_Split
	Kind          isRoutingNode_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingNode) Reset() {
	*x = RoutingNode{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingNode) ProtoMessage() {}

func (x *RoutingNode) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingNode.ProtoReflect.Descriptor instead.
func (*RoutingNode) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *RoutingNode) GetKind() isRoutingNode_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RoutingNode) GetTarget() *RoutingTarget {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Target); ok {
			return x.Target
		}
	}
	return nil
}

func (x *RoutingNode) GetChain() *ChainConfig {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Chain); ok {
			return x.Chain
		}
	}
	return nil
}

func (x *RoutingNode) GetSplit() *SplitConfig {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Split); ok {
			return x.Split
		}
	}
	return nil
}

type isRoutingNode_Kind interface {
	isRoutingNode_Kind()
}

type RoutingNode_Target struct {
	Target *RoutingTarget `protobuf:"bytes,1,opt,name=target,proto3,oneof"`
}

type RoutingNode_Chain struct {
	Chain *ChainConfig `protobuf:"bytes,2,opt,name=chain,proto3,oneof"`
}

type RoutingNode_Split struct {
	Split *SplitConfig `protobuf:"bytes,3,opt,name=split,proto3,oneof"`
}

func (*RoutingNode_Target) isRoutingNode_Kind() {}

func (*RoutingNode_Chain) isRoutingNode_Kind() {}

func (*RoutingNode_Split) isRoutingNode_Kind() {}

// RoutingTarget is a leaf node naming a provider and optional backend model.
type RoutingTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // provider name (matches llm.providers map key)
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`       // backend model name; empty = use client-facing model ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTarget) Reset() {
	*x = RoutingTarget{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTarget) ProtoMessage() {}

func (x *RoutingTarget) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTarget.ProtoReflect.Descriptor instead.
func (*RoutingTarget) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RoutingTarget) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RoutingTarget) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ChainConfig tries children in order; stops at the first success.
type ChainConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retry         *RetryPolicy           `protobuf:"bytes,1,opt,name=retry,proto3" json:"retry,omitempty"`
	Children      []*RoutingNode         `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainConfig) Reset() {
	*x = ChainConfig{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainConfig) ProtoMessage() {}

func (x *ChainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainConfig.ProtoReflect.Descriptor instead.
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{3}
}

func (x *ChainConfig) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *ChainConfig) GetChildren() []*RoutingNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// RetryPolicy maps to Envoy's retry semantics.
type RetryPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RetryOn         string                 `protobuf:"bytes,1,opt,name=retry_on,json=retryOn,proto3" json:"retry_on,omitempty"` // e.g. "connect-failure,reset,5xx"
	PerTryTimeoutMs int32                  `protobuf:"varint,2,opt,name=per_try_timeout_ms,json=perTryTimeoutMs,proto3" json:"per_try_timeout_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{4}
}

func (x *RetryPolicy) GetRetryOn() string {
	if x != nil {
		return x.RetryOn
	}
	return ""
}

func (x *RetryPolicy) GetPerTryTimeoutMs() int32 {
	if x != nil {
		return x.PerTryTimeoutMs
	}
	return 0
}

// SplitConfig samples one child per request by weight (weights must sum to 100).
type SplitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*SplitChild          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitConfig) Reset() {
	*x = SplitConfig{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitConfig) ProtoMessage() {}

func (x *SplitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitConfig.ProtoReflect.Descriptor instead.
func (*SplitConfig) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{5}
}

func (x *SplitConfig) GetChildren() []*SplitChild {
	if x != nil {
		return x.Children
	}
	return nil
}

type SplitChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        int32                  `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Node          *RoutingNode           `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitChild) Reset() {
	*x = SplitChild{}
	mi := &file_orange_routing_v1_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitChild) ProtoMessage() {}

func (x *SplitChild) ProtoReflect() protoreflect.Message {
	mi := &file_orange_routing_v1_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitChild.ProtoReflect.Descriptor instead.
func (*SplitChild) Descriptor() ([]byte, []int) {
	return file_orange_routing_v1_routing_proto_rawDescGZIP(), []int{6}
}

func (x *SplitChild) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SplitChild) GetNode() *RoutingNode {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_orange_routing_v1_routing_proto protoreflect.FileDescriptor

const file_orange_routing_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\x1forange/routing/v1/routing.proto\x12\x11orange.routing.v1\"`\n" +
	"\x0fRoutingOverride\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x122\n" +
	"\x04node\x18\x02 \x01(\v2\x1e.orange.routing.v1.RoutingNodeR\x04node\"\xc1\x01\n" +
	"\vRoutingNode\x12:\n" +
	"\x06target\x18\x01 \x01(\v2 .orange.routing.v1.RoutingTargetH\x00R\x06target\x126\n" +
	"\x05chain\x18\x02 \x01(\v2\x1e.orange.routing.v1.ChainConfigH\x00R\x05chain\x126\n" +
	"\x05split\x18\x03 \x01(\v2\x1e.orange.routing.v1.SplitConfigH\x00R\x05splitB\x06\n" +
	"\x04kind\"A\n" +
	"\rRoutingTarget\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\x7f\n" +
	"\vChainConfig\x124\n" +
	"\x05retry\x18\x01 \x01(\v2\x1e.orange.routing.v1.RetryPolicyR\x05retry\x12:\n" +
	"\bchildren\x18\x02 \x03(\v2\x1e.orange.routing.v1.RoutingNodeR\bchildren\"U\n" +
	"\vRetryPolicy\x12\x19\n" +
	"\bretry_on\x18\x01 \x01(\tR\aretryOn\x12+\n" +
	"\x12per_try_timeout_ms\x18\x02 \x01(\x05R\x0fperTryTimeoutMs\"H\n" +
	"\vSplitConfig\x129\n" +
	"\bchildren\x18\x01 \x03(\v2\x1d.orange.routing.v1.SplitChildR\bchildren\"X\n" +
	"\n" +
	"SplitChild\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x05R\x06weight\x122\n" +
	"\x04node\x18\x02 \x01(\v2\x1e.orange.routing.v1.RoutingNodeR\x04nodeB\xd3\x01\n" +
	"\x15com.orange.routing.v1B\fRoutingProtoP\x01ZFgithub.com/dio/transit/examples/orange/api/orange/routing/v1;routingv1\xa2\x02\x03ORX\xaa\x02\x11Orange.Routing.V1\xca\x02\x11Orange\\Routing\\V1\xe2\x02\x1dOrange\\Routing\\V1\\GPBMetadata\xea\x02\x13Orange::Routing::V1b\x06proto3"

var (
	file_orange_routing_v1_routing_proto_rawDescOnce sync.Once
	file_orange_routing_v1_routing_proto_rawDescData []byte
)

func file_orange_routing_v1_routing_proto_rawDescGZIP() []byte {
	file_orange_routing_v1_routing_proto_rawDescOnce.Do(func() {
		file_orange_routing_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_routing_v1_routing_proto_rawDesc), len(file_orange_routing_v1_routing_proto_rawDesc)))
	})
	return file_orange_routing_v1_routing_proto_rawDescData
}

var file_orange_routing_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orange_routing_v1_routing_proto_goTypes = []any{
	(*RoutingOverride)(nil), // 0: orange.routing.v1.RoutingOverride
	(*RoutingNode)(nil),     // 1: orange.routing.v1.RoutingNode
	(*RoutingTarget)(nil),   // 2: orange.routing.v1.RoutingTarget
	(*ChainConfig)(nil),     // 3: orange.routing.v1.ChainConfig
	(*RetryPolicy)(nil),     // 4: orange.routing.v1.RetryPolicy
	(*SplitConfig)(nil),     // 5: orange.routing.v1.SplitConfig
	(*SplitChild)(nil),      // 6: orange.routing.v1.SplitChild
}
var file_orange_routing_v1_routing_proto_depIdxs = []int32{
	1, // 0: orange.routing.v1.RoutingOverride.node:type_name -> orange.routing.v1.RoutingNode
	2, // 1: orange.routing.v1.RoutingNode.target:type_name -> orange.routing.v1.RoutingTarget
	3, // 2: orange.routing.v1.RoutingNode.chain:type_name -> orange.routing.v1.ChainConfig
	5, // 3: orange.routing.v1.RoutingNode.split:type_name -> orange.routing.v1.SplitConfig
	4, // 4: orange.routing.v1.ChainConfig.retry:type_name -> orange.routing.v1.RetryPolicy
	1, // 5: orange.routing.v1.ChainConfig.children:type_name -> orange.routing.v1.RoutingNode
	6, // 6: orange.routing.v1.SplitConfig.children:type_name -> orange.routing.v1.SplitChild
	1, // 7: orange.routing.v1.SplitChild.node:type_name -> orange.routing.v1.RoutingNode
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_orange_routing_v1_routing_proto_init() }
func file_orange_routing_v1_routing_proto_init() {
	if File_orange_routing_v1_routing_proto != nil {
		return
	}
	file_orange_routing_v1_routing_proto_msgTypes[1].OneofWrappers = []any{
		(*RoutingNode_Target)(nil),
		(*RoutingNode_Chain)(nil),
		(*RoutingNode_Split)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_routing_v1_routing_proto_rawDesc), len(file_orange_routing_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orange_routing_v1_routing_proto_goTypes,
		DependencyIndexes: file_orange_routing_v1_routing_proto_depIdxs,
		MessageInfos:      file_orange_routing_v1_routing_proto_msgTypes,
	}.Build()
	File_orange_routing_v1_routing_proto = out.File
	file_orange_routing_v1_routing_proto_goTypes = nil
	file_orange_routing_v1_routing_proto_depIdxs = nil
}
