// admin.proto — KeyAdminService: Key, PASETOToken, and KeySecret management.
//
// A Key is permanently bound to a single Workspace and a single User.
// key_format is always "paseto_v4.public" (Ed25519).
// key_id is server-assigned as a UUID7.
//
// PASETOToken records metadata and hash of an issued PASETO v4 token;
// the token itself is never stored.
//
// KeySecret (BYOK) is a user-supplied versioned upstream credential bound
// to a specific Key. It overrides the Workspace Secret during request dispatch.
//
// Authentication: every RPC requires AUTH_TYPE_API_KEY with scope "admin".
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/key/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/transit/examples/orange/api/orange/key/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KeyAdminServiceName is the fully-qualified name of the KeyAdminService service.
	KeyAdminServiceName = "orange.key.admin.v1.KeyAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KeyAdminServiceCreateKeyProcedure is the fully-qualified name of the KeyAdminService's CreateKey
	// RPC.
	KeyAdminServiceCreateKeyProcedure = "/orange.key.admin.v1.KeyAdminService/CreateKey"
	// KeyAdminServiceGetKeyProcedure is the fully-qualified name of the KeyAdminService's GetKey RPC.
	KeyAdminServiceGetKeyProcedure = "/orange.key.admin.v1.KeyAdminService/GetKey"
	// KeyAdminServiceListKeysProcedure is the fully-qualified name of the KeyAdminService's ListKeys
	// RPC.
	KeyAdminServiceListKeysProcedure = "/orange.key.admin.v1.KeyAdminService/ListKeys"
	// KeyAdminServiceUpdateKeyProcedure is the fully-qualified name of the KeyAdminService's UpdateKey
	// RPC.
	KeyAdminServiceUpdateKeyProcedure = "/orange.key.admin.v1.KeyAdminService/UpdateKey"
	// KeyAdminServiceDeleteKeyProcedure is the fully-qualified name of the KeyAdminService's DeleteKey
	// RPC.
	KeyAdminServiceDeleteKeyProcedure = "/orange.key.admin.v1.KeyAdminService/DeleteKey"
	// KeyAdminServiceIssueTokenProcedure is the fully-qualified name of the KeyAdminService's
	// IssueToken RPC.
	KeyAdminServiceIssueTokenProcedure = "/orange.key.admin.v1.KeyAdminService/IssueToken"
	// KeyAdminServiceGetTokenProcedure is the fully-qualified name of the KeyAdminService's GetToken
	// RPC.
	KeyAdminServiceGetTokenProcedure = "/orange.key.admin.v1.KeyAdminService/GetToken"
	// KeyAdminServiceListTokensProcedure is the fully-qualified name of the KeyAdminService's
	// ListTokens RPC.
	KeyAdminServiceListTokensProcedure = "/orange.key.admin.v1.KeyAdminService/ListTokens"
	// KeyAdminServiceRevokeTokenProcedure is the fully-qualified name of the KeyAdminService's
	// RevokeToken RPC.
	KeyAdminServiceRevokeTokenProcedure = "/orange.key.admin.v1.KeyAdminService/RevokeToken"
	// KeyAdminServiceCreateKeySecretProcedure is the fully-qualified name of the KeyAdminService's
	// CreateKeySecret RPC.
	KeyAdminServiceCreateKeySecretProcedure = "/orange.key.admin.v1.KeyAdminService/CreateKeySecret"
	// KeyAdminServiceGetKeySecretProcedure is the fully-qualified name of the KeyAdminService's
	// GetKeySecret RPC.
	KeyAdminServiceGetKeySecretProcedure = "/orange.key.admin.v1.KeyAdminService/GetKeySecret"
	// KeyAdminServiceListKeySecretsProcedure is the fully-qualified name of the KeyAdminService's
	// ListKeySecrets RPC.
	KeyAdminServiceListKeySecretsProcedure = "/orange.key.admin.v1.KeyAdminService/ListKeySecrets"
	// KeyAdminServiceRotateKeySecretProcedure is the fully-qualified name of the KeyAdminService's
	// RotateKeySecret RPC.
	KeyAdminServiceRotateKeySecretProcedure = "/orange.key.admin.v1.KeyAdminService/RotateKeySecret"
	// KeyAdminServiceDeleteKeySecretProcedure is the fully-qualified name of the KeyAdminService's
	// DeleteKeySecret RPC.
	KeyAdminServiceDeleteKeySecretProcedure = "/orange.key.admin.v1.KeyAdminService/DeleteKeySecret"
)

// KeyAdminServiceClient is a client for the orange.key.admin.v1.KeyAdminService service.
type KeyAdminServiceClient interface {
	CreateKey(context.Context, *connect.Request[v1.CreateKeyRequest]) (*connect.Response[v1.CreateKeyResponse], error)
	GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error)
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error)
	UpdateKey(context.Context, *connect.Request[v1.UpdateKeyRequest]) (*connect.Response[v1.UpdateKeyResponse], error)
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	// IssueToken issues a new PASETO v4 token and stores its metadata.
	IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error)
	// GetToken returns metadata for a previously issued token.
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// ListTokens lists token metadata records for a key.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// RevokeToken marks a token as revoked. The token itself is never stored.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	// CreateKeySecret creates a versioned upstream credential bound to a key.
	CreateKeySecret(context.Context, *connect.Request[v1.CreateKeySecretRequest]) (*connect.Response[v1.CreateKeySecretResponse], error)
	// GetKeySecret returns a KeySecret record (value is never returned).
	GetKeySecret(context.Context, *connect.Request[v1.GetKeySecretRequest]) (*connect.Response[v1.GetKeySecretResponse], error)
	// ListKeySecrets lists all KeySecrets for a key.
	ListKeySecrets(context.Context, *connect.Request[v1.ListKeySecretsRequest]) (*connect.Response[v1.ListKeySecretsResponse], error)
	// RotateKeySecret creates a new version of a KeySecret.
	RotateKeySecret(context.Context, *connect.Request[v1.RotateKeySecretRequest]) (*connect.Response[v1.RotateKeySecretResponse], error)
	// DeleteKeySecret permanently removes a KeySecret and all its versions.
	DeleteKeySecret(context.Context, *connect.Request[v1.DeleteKeySecretRequest]) (*connect.Response[v1.DeleteKeySecretResponse], error)
}

// NewKeyAdminServiceClient constructs a client for the orange.key.admin.v1.KeyAdminService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKeyAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KeyAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	keyAdminServiceMethods := v1.File_orange_key_admin_v1_admin_proto.Services().ByName("KeyAdminService").Methods()
	return &keyAdminServiceClient{
		createKey: connect.NewClient[v1.CreateKeyRequest, v1.CreateKeyResponse](
			httpClient,
			baseURL+KeyAdminServiceCreateKeyProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("CreateKey")),
			connect.WithClientOptions(opts...),
		),
		getKey: connect.NewClient[v1.GetKeyRequest, v1.GetKeyResponse](
			httpClient,
			baseURL+KeyAdminServiceGetKeyProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("GetKey")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listKeys: connect.NewClient[v1.ListKeysRequest, v1.ListKeysResponse](
			httpClient,
			baseURL+KeyAdminServiceListKeysProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("ListKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateKey: connect.NewClient[v1.UpdateKeyRequest, v1.UpdateKeyResponse](
			httpClient,
			baseURL+KeyAdminServiceUpdateKeyProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("UpdateKey")),
			connect.WithClientOptions(opts...),
		),
		deleteKey: connect.NewClient[v1.DeleteKeyRequest, v1.DeleteKeyResponse](
			httpClient,
			baseURL+KeyAdminServiceDeleteKeyProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("DeleteKey")),
			connect.WithClientOptions(opts...),
		),
		issueToken: connect.NewClient[v1.IssueTokenRequest, v1.IssueTokenResponse](
			httpClient,
			baseURL+KeyAdminServiceIssueTokenProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("IssueToken")),
			connect.WithClientOptions(opts...),
		),
		getToken: connect.NewClient[v1.GetTokenRequest, v1.GetTokenResponse](
			httpClient,
			baseURL+KeyAdminServiceGetTokenProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("GetToken")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listTokens: connect.NewClient[v1.ListTokensRequest, v1.ListTokensResponse](
			httpClient,
			baseURL+KeyAdminServiceListTokensProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("ListTokens")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[v1.RevokeTokenRequest, v1.RevokeTokenResponse](
			httpClient,
			baseURL+KeyAdminServiceRevokeTokenProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("RevokeToken")),
			connect.WithClientOptions(opts...),
		),
		createKeySecret: connect.NewClient[v1.CreateKeySecretRequest, v1.CreateKeySecretResponse](
			httpClient,
			baseURL+KeyAdminServiceCreateKeySecretProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("CreateKeySecret")),
			connect.WithClientOptions(opts...),
		),
		getKeySecret: connect.NewClient[v1.GetKeySecretRequest, v1.GetKeySecretResponse](
			httpClient,
			baseURL+KeyAdminServiceGetKeySecretProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("GetKeySecret")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listKeySecrets: connect.NewClient[v1.ListKeySecretsRequest, v1.ListKeySecretsResponse](
			httpClient,
			baseURL+KeyAdminServiceListKeySecretsProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("ListKeySecrets")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		rotateKeySecret: connect.NewClient[v1.RotateKeySecretRequest, v1.RotateKeySecretResponse](
			httpClient,
			baseURL+KeyAdminServiceRotateKeySecretProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("RotateKeySecret")),
			connect.WithClientOptions(opts...),
		),
		deleteKeySecret: connect.NewClient[v1.DeleteKeySecretRequest, v1.DeleteKeySecretResponse](
			httpClient,
			baseURL+KeyAdminServiceDeleteKeySecretProcedure,
			connect.WithSchema(keyAdminServiceMethods.ByName("DeleteKeySecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// keyAdminServiceClient implements KeyAdminServiceClient.
type keyAdminServiceClient struct {
	createKey       *connect.Client[v1.CreateKeyRequest, v1.CreateKeyResponse]
	getKey          *connect.Client[v1.GetKeyRequest, v1.GetKeyResponse]
	listKeys        *connect.Client[v1.ListKeysRequest, v1.ListKeysResponse]
	updateKey       *connect.Client[v1.UpdateKeyRequest, v1.UpdateKeyResponse]
	deleteKey       *connect.Client[v1.DeleteKeyRequest, v1.DeleteKeyResponse]
	issueToken      *connect.Client[v1.IssueTokenRequest, v1.IssueTokenResponse]
	getToken        *connect.Client[v1.GetTokenRequest, v1.GetTokenResponse]
	listTokens      *connect.Client[v1.ListTokensRequest, v1.ListTokensResponse]
	revokeToken     *connect.Client[v1.RevokeTokenRequest, v1.RevokeTokenResponse]
	createKeySecret *connect.Client[v1.CreateKeySecretRequest, v1.CreateKeySecretResponse]
	getKeySecret    *connect.Client[v1.GetKeySecretRequest, v1.GetKeySecretResponse]
	listKeySecrets  *connect.Client[v1.ListKeySecretsRequest, v1.ListKeySecretsResponse]
	rotateKeySecret *connect.Client[v1.RotateKeySecretRequest, v1.RotateKeySecretResponse]
	deleteKeySecret *connect.Client[v1.DeleteKeySecretRequest, v1.DeleteKeySecretResponse]
}

// CreateKey calls orange.key.admin.v1.KeyAdminService.CreateKey.
func (c *keyAdminServiceClient) CreateKey(ctx context.Context, req *connect.Request[v1.CreateKeyRequest]) (*connect.Response[v1.CreateKeyResponse], error) {
	return c.createKey.CallUnary(ctx, req)
}

// GetKey calls orange.key.admin.v1.KeyAdminService.GetKey.
func (c *keyAdminServiceClient) GetKey(ctx context.Context, req *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error) {
	return c.getKey.CallUnary(ctx, req)
}

// ListKeys calls orange.key.admin.v1.KeyAdminService.ListKeys.
func (c *keyAdminServiceClient) ListKeys(ctx context.Context, req *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error) {
	return c.listKeys.CallUnary(ctx, req)
}

// UpdateKey calls orange.key.admin.v1.KeyAdminService.UpdateKey.
func (c *keyAdminServiceClient) UpdateKey(ctx context.Context, req *connect.Request[v1.UpdateKeyRequest]) (*connect.Response[v1.UpdateKeyResponse], error) {
	return c.updateKey.CallUnary(ctx, req)
}

// DeleteKey calls orange.key.admin.v1.KeyAdminService.DeleteKey.
func (c *keyAdminServiceClient) DeleteKey(ctx context.Context, req *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return c.deleteKey.CallUnary(ctx, req)
}

// IssueToken calls orange.key.admin.v1.KeyAdminService.IssueToken.
func (c *keyAdminServiceClient) IssueToken(ctx context.Context, req *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error) {
	return c.issueToken.CallUnary(ctx, req)
}

// GetToken calls orange.key.admin.v1.KeyAdminService.GetToken.
func (c *keyAdminServiceClient) GetToken(ctx context.Context, req *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return c.getToken.CallUnary(ctx, req)
}

// ListTokens calls orange.key.admin.v1.KeyAdminService.ListTokens.
func (c *keyAdminServiceClient) ListTokens(ctx context.Context, req *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return c.listTokens.CallUnary(ctx, req)
}

// RevokeToken calls orange.key.admin.v1.KeyAdminService.RevokeToken.
func (c *keyAdminServiceClient) RevokeToken(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// CreateKeySecret calls orange.key.admin.v1.KeyAdminService.CreateKeySecret.
func (c *keyAdminServiceClient) CreateKeySecret(ctx context.Context, req *connect.Request[v1.CreateKeySecretRequest]) (*connect.Response[v1.CreateKeySecretResponse], error) {
	return c.createKeySecret.CallUnary(ctx, req)
}

// GetKeySecret calls orange.key.admin.v1.KeyAdminService.GetKeySecret.
func (c *keyAdminServiceClient) GetKeySecret(ctx context.Context, req *connect.Request[v1.GetKeySecretRequest]) (*connect.Response[v1.GetKeySecretResponse], error) {
	return c.getKeySecret.CallUnary(ctx, req)
}

// ListKeySecrets calls orange.key.admin.v1.KeyAdminService.ListKeySecrets.
func (c *keyAdminServiceClient) ListKeySecrets(ctx context.Context, req *connect.Request[v1.ListKeySecretsRequest]) (*connect.Response[v1.ListKeySecretsResponse], error) {
	return c.listKeySecrets.CallUnary(ctx, req)
}

// RotateKeySecret calls orange.key.admin.v1.KeyAdminService.RotateKeySecret.
func (c *keyAdminServiceClient) RotateKeySecret(ctx context.Context, req *connect.Request[v1.RotateKeySecretRequest]) (*connect.Response[v1.RotateKeySecretResponse], error) {
	return c.rotateKeySecret.CallUnary(ctx, req)
}

// DeleteKeySecret calls orange.key.admin.v1.KeyAdminService.DeleteKeySecret.
func (c *keyAdminServiceClient) DeleteKeySecret(ctx context.Context, req *connect.Request[v1.DeleteKeySecretRequest]) (*connect.Response[v1.DeleteKeySecretResponse], error) {
	return c.deleteKeySecret.CallUnary(ctx, req)
}

// KeyAdminServiceHandler is an implementation of the orange.key.admin.v1.KeyAdminService service.
type KeyAdminServiceHandler interface {
	CreateKey(context.Context, *connect.Request[v1.CreateKeyRequest]) (*connect.Response[v1.CreateKeyResponse], error)
	GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error)
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error)
	UpdateKey(context.Context, *connect.Request[v1.UpdateKeyRequest]) (*connect.Response[v1.UpdateKeyResponse], error)
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	// IssueToken issues a new PASETO v4 token and stores its metadata.
	IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error)
	// GetToken returns metadata for a previously issued token.
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// ListTokens lists token metadata records for a key.
	ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error)
	// RevokeToken marks a token as revoked. The token itself is never stored.
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
	// CreateKeySecret creates a versioned upstream credential bound to a key.
	CreateKeySecret(context.Context, *connect.Request[v1.CreateKeySecretRequest]) (*connect.Response[v1.CreateKeySecretResponse], error)
	// GetKeySecret returns a KeySecret record (value is never returned).
	GetKeySecret(context.Context, *connect.Request[v1.GetKeySecretRequest]) (*connect.Response[v1.GetKeySecretResponse], error)
	// ListKeySecrets lists all KeySecrets for a key.
	ListKeySecrets(context.Context, *connect.Request[v1.ListKeySecretsRequest]) (*connect.Response[v1.ListKeySecretsResponse], error)
	// RotateKeySecret creates a new version of a KeySecret.
	RotateKeySecret(context.Context, *connect.Request[v1.RotateKeySecretRequest]) (*connect.Response[v1.RotateKeySecretResponse], error)
	// DeleteKeySecret permanently removes a KeySecret and all its versions.
	DeleteKeySecret(context.Context, *connect.Request[v1.DeleteKeySecretRequest]) (*connect.Response[v1.DeleteKeySecretResponse], error)
}

// NewKeyAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKeyAdminServiceHandler(svc KeyAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	keyAdminServiceMethods := v1.File_orange_key_admin_v1_admin_proto.Services().ByName("KeyAdminService").Methods()
	keyAdminServiceCreateKeyHandler := connect.NewUnaryHandler(
		KeyAdminServiceCreateKeyProcedure,
		svc.CreateKey,
		connect.WithSchema(keyAdminServiceMethods.ByName("CreateKey")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceGetKeyHandler := connect.NewUnaryHandler(
		KeyAdminServiceGetKeyProcedure,
		svc.GetKey,
		connect.WithSchema(keyAdminServiceMethods.ByName("GetKey")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceListKeysHandler := connect.NewUnaryHandler(
		KeyAdminServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(keyAdminServiceMethods.ByName("ListKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceUpdateKeyHandler := connect.NewUnaryHandler(
		KeyAdminServiceUpdateKeyProcedure,
		svc.UpdateKey,
		connect.WithSchema(keyAdminServiceMethods.ByName("UpdateKey")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceDeleteKeyHandler := connect.NewUnaryHandler(
		KeyAdminServiceDeleteKeyProcedure,
		svc.DeleteKey,
		connect.WithSchema(keyAdminServiceMethods.ByName("DeleteKey")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceIssueTokenHandler := connect.NewUnaryHandler(
		KeyAdminServiceIssueTokenProcedure,
		svc.IssueToken,
		connect.WithSchema(keyAdminServiceMethods.ByName("IssueToken")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceGetTokenHandler := connect.NewUnaryHandler(
		KeyAdminServiceGetTokenProcedure,
		svc.GetToken,
		connect.WithSchema(keyAdminServiceMethods.ByName("GetToken")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceListTokensHandler := connect.NewUnaryHandler(
		KeyAdminServiceListTokensProcedure,
		svc.ListTokens,
		connect.WithSchema(keyAdminServiceMethods.ByName("ListTokens")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceRevokeTokenHandler := connect.NewUnaryHandler(
		KeyAdminServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(keyAdminServiceMethods.ByName("RevokeToken")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceCreateKeySecretHandler := connect.NewUnaryHandler(
		KeyAdminServiceCreateKeySecretProcedure,
		svc.CreateKeySecret,
		connect.WithSchema(keyAdminServiceMethods.ByName("CreateKeySecret")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceGetKeySecretHandler := connect.NewUnaryHandler(
		KeyAdminServiceGetKeySecretProcedure,
		svc.GetKeySecret,
		connect.WithSchema(keyAdminServiceMethods.ByName("GetKeySecret")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceListKeySecretsHandler := connect.NewUnaryHandler(
		KeyAdminServiceListKeySecretsProcedure,
		svc.ListKeySecrets,
		connect.WithSchema(keyAdminServiceMethods.ByName("ListKeySecrets")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceRotateKeySecretHandler := connect.NewUnaryHandler(
		KeyAdminServiceRotateKeySecretProcedure,
		svc.RotateKeySecret,
		connect.WithSchema(keyAdminServiceMethods.ByName("RotateKeySecret")),
		connect.WithHandlerOptions(opts...),
	)
	keyAdminServiceDeleteKeySecretHandler := connect.NewUnaryHandler(
		KeyAdminServiceDeleteKeySecretProcedure,
		svc.DeleteKeySecret,
		connect.WithSchema(keyAdminServiceMethods.ByName("DeleteKeySecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.key.admin.v1.KeyAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KeyAdminServiceCreateKeyProcedure:
			keyAdminServiceCreateKeyHandler.ServeHTTP(w, r)
		case KeyAdminServiceGetKeyProcedure:
			keyAdminServiceGetKeyHandler.ServeHTTP(w, r)
		case KeyAdminServiceListKeysProcedure:
			keyAdminServiceListKeysHandler.ServeHTTP(w, r)
		case KeyAdminServiceUpdateKeyProcedure:
			keyAdminServiceUpdateKeyHandler.ServeHTTP(w, r)
		case KeyAdminServiceDeleteKeyProcedure:
			keyAdminServiceDeleteKeyHandler.ServeHTTP(w, r)
		case KeyAdminServiceIssueTokenProcedure:
			keyAdminServiceIssueTokenHandler.ServeHTTP(w, r)
		case KeyAdminServiceGetTokenProcedure:
			keyAdminServiceGetTokenHandler.ServeHTTP(w, r)
		case KeyAdminServiceListTokensProcedure:
			keyAdminServiceListTokensHandler.ServeHTTP(w, r)
		case KeyAdminServiceRevokeTokenProcedure:
			keyAdminServiceRevokeTokenHandler.ServeHTTP(w, r)
		case KeyAdminServiceCreateKeySecretProcedure:
			keyAdminServiceCreateKeySecretHandler.ServeHTTP(w, r)
		case KeyAdminServiceGetKeySecretProcedure:
			keyAdminServiceGetKeySecretHandler.ServeHTTP(w, r)
		case KeyAdminServiceListKeySecretsProcedure:
			keyAdminServiceListKeySecretsHandler.ServeHTTP(w, r)
		case KeyAdminServiceRotateKeySecretProcedure:
			keyAdminServiceRotateKeySecretHandler.ServeHTTP(w, r)
		case KeyAdminServiceDeleteKeySecretProcedure:
			keyAdminServiceDeleteKeySecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKeyAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKeyAdminServiceHandler struct{}

func (UnimplementedKeyAdminServiceHandler) CreateKey(context.Context, *connect.Request[v1.CreateKeyRequest]) (*connect.Response[v1.CreateKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.CreateKey is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) GetKey(context.Context, *connect.Request[v1.GetKeyRequest]) (*connect.Response[v1.GetKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.GetKey is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.ListKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.ListKeys is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) UpdateKey(context.Context, *connect.Request[v1.UpdateKeyRequest]) (*connect.Response[v1.UpdateKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.UpdateKey is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.DeleteKey is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.IssueToken is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.GetToken is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) ListTokens(context.Context, *connect.Request[v1.ListTokensRequest]) (*connect.Response[v1.ListTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.ListTokens is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.RevokeToken is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) CreateKeySecret(context.Context, *connect.Request[v1.CreateKeySecretRequest]) (*connect.Response[v1.CreateKeySecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.CreateKeySecret is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) GetKeySecret(context.Context, *connect.Request[v1.GetKeySecretRequest]) (*connect.Response[v1.GetKeySecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.GetKeySecret is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) ListKeySecrets(context.Context, *connect.Request[v1.ListKeySecretsRequest]) (*connect.Response[v1.ListKeySecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.ListKeySecrets is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) RotateKeySecret(context.Context, *connect.Request[v1.RotateKeySecretRequest]) (*connect.Response[v1.RotateKeySecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.RotateKeySecret is not implemented"))
}

func (UnimplementedKeyAdminServiceHandler) DeleteKeySecret(context.Context, *connect.Request[v1.DeleteKeySecretRequest]) (*connect.Response[v1.DeleteKeySecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.key.admin.v1.KeyAdminService.DeleteKeySecret is not implemented"))
}
