ARG TARGETARCH

FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETARCH

COPY dist/cluster-async-router-demo.linux-${TARGETARCH} /cluster-async-router-demo

ENTRYPOINT ["/cluster-async-router-demo"]
