apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: transit-system
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
      kubernetes:
        deploy:
          type: GatewayNamespace
        watch:
          type: Namespaces
          namespaces:
          - transit-system
          - transit-dataplane
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableEnvoyPatchPolicy: true
    runtimeFlags:
      enabled:
      - XDSNameSchemeV2
