// admin.proto — PolicyAdminService: policy lifecycle management.
//
// A Policy attaches rate-limit rules at Project, Workspace, or Key scope.
// Policy types:
//   floor    — hard guardrails set by org admins; cannot be narrowed by lower scopes
//   flexible — constraints that workspace/key owners may further restrict
//
// Evaluation order: Project → Workspace → Key
// Project-level policies establish organizational guardrails.
// Workspace and Key policies may only narrow, never widen Project constraints.
//
// PolicyRule mirrors the RateLimitRule from the config system design:
// zero values mean "unconstrained" for that dimension. Multiple limits on the
// same rule are independent — whichever is exhausted first triggers on_exceed.
// All matching rules across all scopes accumulate and are enforced simultaneously.
//
// policy_id is server-assigned as a UUID7.
//
// Authentication: every RPC requires AUTH_TYPE_API_KEY with scope "admin".
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/policy/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/transit/examples/orange/api/orange/policy/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PolicyAdminServiceName is the fully-qualified name of the PolicyAdminService service.
	PolicyAdminServiceName = "orange.policy.admin.v1.PolicyAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PolicyAdminServiceCreatePolicyProcedure is the fully-qualified name of the PolicyAdminService's
	// CreatePolicy RPC.
	PolicyAdminServiceCreatePolicyProcedure = "/orange.policy.admin.v1.PolicyAdminService/CreatePolicy"
	// PolicyAdminServiceGetPolicyProcedure is the fully-qualified name of the PolicyAdminService's
	// GetPolicy RPC.
	PolicyAdminServiceGetPolicyProcedure = "/orange.policy.admin.v1.PolicyAdminService/GetPolicy"
	// PolicyAdminServiceListPoliciesProcedure is the fully-qualified name of the PolicyAdminService's
	// ListPolicies RPC.
	PolicyAdminServiceListPoliciesProcedure = "/orange.policy.admin.v1.PolicyAdminService/ListPolicies"
	// PolicyAdminServiceUpdatePolicyProcedure is the fully-qualified name of the PolicyAdminService's
	// UpdatePolicy RPC.
	PolicyAdminServiceUpdatePolicyProcedure = "/orange.policy.admin.v1.PolicyAdminService/UpdatePolicy"
	// PolicyAdminServiceDeletePolicyProcedure is the fully-qualified name of the PolicyAdminService's
	// DeletePolicy RPC.
	PolicyAdminServiceDeletePolicyProcedure = "/orange.policy.admin.v1.PolicyAdminService/DeletePolicy"
)

// PolicyAdminServiceClient is a client for the orange.policy.admin.v1.PolicyAdminService service.
type PolicyAdminServiceClient interface {
	CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error)
	GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error)
	DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error)
}

// NewPolicyAdminServiceClient constructs a client for the orange.policy.admin.v1.PolicyAdminService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPolicyAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PolicyAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	policyAdminServiceMethods := v1.File_orange_policy_admin_v1_admin_proto.Services().ByName("PolicyAdminService").Methods()
	return &policyAdminServiceClient{
		createPolicy: connect.NewClient[v1.CreatePolicyRequest, v1.CreatePolicyResponse](
			httpClient,
			baseURL+PolicyAdminServiceCreatePolicyProcedure,
			connect.WithSchema(policyAdminServiceMethods.ByName("CreatePolicy")),
			connect.WithClientOptions(opts...),
		),
		getPolicy: connect.NewClient[v1.GetPolicyRequest, v1.GetPolicyResponse](
			httpClient,
			baseURL+PolicyAdminServiceGetPolicyProcedure,
			connect.WithSchema(policyAdminServiceMethods.ByName("GetPolicy")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicies: connect.NewClient[v1.ListPoliciesRequest, v1.ListPoliciesResponse](
			httpClient,
			baseURL+PolicyAdminServiceListPoliciesProcedure,
			connect.WithSchema(policyAdminServiceMethods.ByName("ListPolicies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updatePolicy: connect.NewClient[v1.UpdatePolicyRequest, v1.UpdatePolicyResponse](
			httpClient,
			baseURL+PolicyAdminServiceUpdatePolicyProcedure,
			connect.WithSchema(policyAdminServiceMethods.ByName("UpdatePolicy")),
			connect.WithClientOptions(opts...),
		),
		deletePolicy: connect.NewClient[v1.DeletePolicyRequest, v1.DeletePolicyResponse](
			httpClient,
			baseURL+PolicyAdminServiceDeletePolicyProcedure,
			connect.WithSchema(policyAdminServiceMethods.ByName("DeletePolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// policyAdminServiceClient implements PolicyAdminServiceClient.
type policyAdminServiceClient struct {
	createPolicy *connect.Client[v1.CreatePolicyRequest, v1.CreatePolicyResponse]
	getPolicy    *connect.Client[v1.GetPolicyRequest, v1.GetPolicyResponse]
	listPolicies *connect.Client[v1.ListPoliciesRequest, v1.ListPoliciesResponse]
	updatePolicy *connect.Client[v1.UpdatePolicyRequest, v1.UpdatePolicyResponse]
	deletePolicy *connect.Client[v1.DeletePolicyRequest, v1.DeletePolicyResponse]
}

// CreatePolicy calls orange.policy.admin.v1.PolicyAdminService.CreatePolicy.
func (c *policyAdminServiceClient) CreatePolicy(ctx context.Context, req *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error) {
	return c.createPolicy.CallUnary(ctx, req)
}

// GetPolicy calls orange.policy.admin.v1.PolicyAdminService.GetPolicy.
func (c *policyAdminServiceClient) GetPolicy(ctx context.Context, req *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error) {
	return c.getPolicy.CallUnary(ctx, req)
}

// ListPolicies calls orange.policy.admin.v1.PolicyAdminService.ListPolicies.
func (c *policyAdminServiceClient) ListPolicies(ctx context.Context, req *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// UpdatePolicy calls orange.policy.admin.v1.PolicyAdminService.UpdatePolicy.
func (c *policyAdminServiceClient) UpdatePolicy(ctx context.Context, req *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error) {
	return c.updatePolicy.CallUnary(ctx, req)
}

// DeletePolicy calls orange.policy.admin.v1.PolicyAdminService.DeletePolicy.
func (c *policyAdminServiceClient) DeletePolicy(ctx context.Context, req *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error) {
	return c.deletePolicy.CallUnary(ctx, req)
}

// PolicyAdminServiceHandler is an implementation of the orange.policy.admin.v1.PolicyAdminService
// service.
type PolicyAdminServiceHandler interface {
	CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error)
	GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error)
	DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error)
}

// NewPolicyAdminServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPolicyAdminServiceHandler(svc PolicyAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	policyAdminServiceMethods := v1.File_orange_policy_admin_v1_admin_proto.Services().ByName("PolicyAdminService").Methods()
	policyAdminServiceCreatePolicyHandler := connect.NewUnaryHandler(
		PolicyAdminServiceCreatePolicyProcedure,
		svc.CreatePolicy,
		connect.WithSchema(policyAdminServiceMethods.ByName("CreatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	policyAdminServiceGetPolicyHandler := connect.NewUnaryHandler(
		PolicyAdminServiceGetPolicyProcedure,
		svc.GetPolicy,
		connect.WithSchema(policyAdminServiceMethods.ByName("GetPolicy")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policyAdminServiceListPoliciesHandler := connect.NewUnaryHandler(
		PolicyAdminServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(policyAdminServiceMethods.ByName("ListPolicies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policyAdminServiceUpdatePolicyHandler := connect.NewUnaryHandler(
		PolicyAdminServiceUpdatePolicyProcedure,
		svc.UpdatePolicy,
		connect.WithSchema(policyAdminServiceMethods.ByName("UpdatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	policyAdminServiceDeletePolicyHandler := connect.NewUnaryHandler(
		PolicyAdminServiceDeletePolicyProcedure,
		svc.DeletePolicy,
		connect.WithSchema(policyAdminServiceMethods.ByName("DeletePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.policy.admin.v1.PolicyAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PolicyAdminServiceCreatePolicyProcedure:
			policyAdminServiceCreatePolicyHandler.ServeHTTP(w, r)
		case PolicyAdminServiceGetPolicyProcedure:
			policyAdminServiceGetPolicyHandler.ServeHTTP(w, r)
		case PolicyAdminServiceListPoliciesProcedure:
			policyAdminServiceListPoliciesHandler.ServeHTTP(w, r)
		case PolicyAdminServiceUpdatePolicyProcedure:
			policyAdminServiceUpdatePolicyHandler.ServeHTTP(w, r)
		case PolicyAdminServiceDeletePolicyProcedure:
			policyAdminServiceDeletePolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPolicyAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPolicyAdminServiceHandler struct{}

func (UnimplementedPolicyAdminServiceHandler) CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.policy.admin.v1.PolicyAdminService.CreatePolicy is not implemented"))
}

func (UnimplementedPolicyAdminServiceHandler) GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.policy.admin.v1.PolicyAdminService.GetPolicy is not implemented"))
}

func (UnimplementedPolicyAdminServiceHandler) ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.policy.admin.v1.PolicyAdminService.ListPolicies is not implemented"))
}

func (UnimplementedPolicyAdminServiceHandler) UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.policy.admin.v1.PolicyAdminService.UpdatePolicy is not implemented"))
}

func (UnimplementedPolicyAdminServiceHandler) DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.policy.admin.v1.PolicyAdminService.DeletePolicy is not implemented"))
}
