// service.proto — SecretResolverService: client-facing secret delivery.
//
// Mirrors the config SnapshotService pattern but for named secrets managed
// by SecretAdminService. There are three entry points:
//
//   Resolve — hot path, per-secret, conditional.
//     The caller presents (workspace_id, realm, secret_id) plus optional
//     freshness hints (if_version, if_checksum). When both hints still match
//     the current store state the server returns Unchanged, saving a full
//     decrypt-and-copy round trip. Returns plaintext material.
//
//   Watch — metadata-only streaming channel.
//     The server pushes a fresh SecretSetSnapshot whenever any secret in the
//     workspace changes, plus Heartbeat on the idle timer to prove liveness.
//     Clients use the metadata to invalidate their per-secret caches before
//     issuing targeted Resolve calls. Watch never carries secret material.
//
//   Fetch — unary cold-start / reconnect equivalent of Watch.
//     Returns the current SecretSetSnapshot or Unchanged when the caller's
//     if_version + if_checksum still match. Also suitable for polling clients
//     that cannot hold a long-lived Watch stream.
//
// Secret material is transmitted only on Resolve. Watch and Fetch carry only
// identity + version + checksum — consumers verify freshness then call Resolve.
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/secret/v1/service.proto

package secretv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/transit/examples/orange/api/orange/secret/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecretResolverServiceName is the fully-qualified name of the SecretResolverService service.
	SecretResolverServiceName = "orange.secret.v1.SecretResolverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretResolverServiceResolveProcedure is the fully-qualified name of the SecretResolverService's
	// Resolve RPC.
	SecretResolverServiceResolveProcedure = "/orange.secret.v1.SecretResolverService/Resolve"
	// SecretResolverServiceWatchProcedure is the fully-qualified name of the SecretResolverService's
	// Watch RPC.
	SecretResolverServiceWatchProcedure = "/orange.secret.v1.SecretResolverService/Watch"
	// SecretResolverServiceFetchProcedure is the fully-qualified name of the SecretResolverService's
	// Fetch RPC.
	SecretResolverServiceFetchProcedure = "/orange.secret.v1.SecretResolverService/Fetch"
)

// SecretResolverServiceClient is a client for the orange.secret.v1.SecretResolverService service.
type SecretResolverServiceClient interface {
	// Resolve is the hot path. Returns plaintext material for one secret.
	// When both if_version and if_checksum match the current store state,
	// returns Unchanged instead of decrypting and copying material.
	Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error)
	// Watch is the metadata-only streaming channel.
	// The server pushes a SecretSetSnapshot on any change in the workspace
	// and emits a Heartbeat on the idle timer to prove liveness.
	// Clients use the snapshot to invalidate caches; material is fetched via Resolve.
	Watch(context.Context, *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.WatchResponse], error)
	// Fetch is the unary cold-start / reconnect equivalent of Watch.
	// Returns the current SecretSetSnapshot or Unchanged when freshness hints match.
	// Also suitable for polling clients that cannot hold a long-lived Watch stream.
	Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error)
}

// NewSecretResolverServiceClient constructs a client for the orange.secret.v1.SecretResolverService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretResolverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretResolverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secretResolverServiceMethods := v1.File_orange_secret_v1_service_proto.Services().ByName("SecretResolverService").Methods()
	return &secretResolverServiceClient{
		resolve: connect.NewClient[v1.ResolveRequest, v1.ResolveResponse](
			httpClient,
			baseURL+SecretResolverServiceResolveProcedure,
			connect.WithSchema(secretResolverServiceMethods.ByName("Resolve")),
			connect.WithClientOptions(opts...),
		),
		watch: connect.NewClient[v1.WatchRequest, v1.WatchResponse](
			httpClient,
			baseURL+SecretResolverServiceWatchProcedure,
			connect.WithSchema(secretResolverServiceMethods.ByName("Watch")),
			connect.WithClientOptions(opts...),
		),
		fetch: connect.NewClient[v1.FetchRequest, v1.FetchResponse](
			httpClient,
			baseURL+SecretResolverServiceFetchProcedure,
			connect.WithSchema(secretResolverServiceMethods.ByName("Fetch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secretResolverServiceClient implements SecretResolverServiceClient.
type secretResolverServiceClient struct {
	resolve *connect.Client[v1.ResolveRequest, v1.ResolveResponse]
	watch   *connect.Client[v1.WatchRequest, v1.WatchResponse]
	fetch   *connect.Client[v1.FetchRequest, v1.FetchResponse]
}

// Resolve calls orange.secret.v1.SecretResolverService.Resolve.
func (c *secretResolverServiceClient) Resolve(ctx context.Context, req *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error) {
	return c.resolve.CallUnary(ctx, req)
}

// Watch calls orange.secret.v1.SecretResolverService.Watch.
func (c *secretResolverServiceClient) Watch(ctx context.Context, req *connect.Request[v1.WatchRequest]) (*connect.ServerStreamForClient[v1.WatchResponse], error) {
	return c.watch.CallServerStream(ctx, req)
}

// Fetch calls orange.secret.v1.SecretResolverService.Fetch.
func (c *secretResolverServiceClient) Fetch(ctx context.Context, req *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error) {
	return c.fetch.CallUnary(ctx, req)
}

// SecretResolverServiceHandler is an implementation of the orange.secret.v1.SecretResolverService
// service.
type SecretResolverServiceHandler interface {
	// Resolve is the hot path. Returns plaintext material for one secret.
	// When both if_version and if_checksum match the current store state,
	// returns Unchanged instead of decrypting and copying material.
	Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error)
	// Watch is the metadata-only streaming channel.
	// The server pushes a SecretSetSnapshot on any change in the workspace
	// and emits a Heartbeat on the idle timer to prove liveness.
	// Clients use the snapshot to invalidate caches; material is fetched via Resolve.
	Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.WatchResponse]) error
	// Fetch is the unary cold-start / reconnect equivalent of Watch.
	// Returns the current SecretSetSnapshot or Unchanged when freshness hints match.
	// Also suitable for polling clients that cannot hold a long-lived Watch stream.
	Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error)
}

// NewSecretResolverServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretResolverServiceHandler(svc SecretResolverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretResolverServiceMethods := v1.File_orange_secret_v1_service_proto.Services().ByName("SecretResolverService").Methods()
	secretResolverServiceResolveHandler := connect.NewUnaryHandler(
		SecretResolverServiceResolveProcedure,
		svc.Resolve,
		connect.WithSchema(secretResolverServiceMethods.ByName("Resolve")),
		connect.WithHandlerOptions(opts...),
	)
	secretResolverServiceWatchHandler := connect.NewServerStreamHandler(
		SecretResolverServiceWatchProcedure,
		svc.Watch,
		connect.WithSchema(secretResolverServiceMethods.ByName("Watch")),
		connect.WithHandlerOptions(opts...),
	)
	secretResolverServiceFetchHandler := connect.NewUnaryHandler(
		SecretResolverServiceFetchProcedure,
		svc.Fetch,
		connect.WithSchema(secretResolverServiceMethods.ByName("Fetch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.secret.v1.SecretResolverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretResolverServiceResolveProcedure:
			secretResolverServiceResolveHandler.ServeHTTP(w, r)
		case SecretResolverServiceWatchProcedure:
			secretResolverServiceWatchHandler.ServeHTTP(w, r)
		case SecretResolverServiceFetchProcedure:
			secretResolverServiceFetchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretResolverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretResolverServiceHandler struct{}

func (UnimplementedSecretResolverServiceHandler) Resolve(context.Context, *connect.Request[v1.ResolveRequest]) (*connect.Response[v1.ResolveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.secret.v1.SecretResolverService.Resolve is not implemented"))
}

func (UnimplementedSecretResolverServiceHandler) Watch(context.Context, *connect.Request[v1.WatchRequest], *connect.ServerStream[v1.WatchResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("orange.secret.v1.SecretResolverService.Watch is not implemented"))
}

func (UnimplementedSecretResolverServiceHandler) Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.secret.v1.SecretResolverService.Fetch is not implemented"))
}
