// snapshot.proto — orange config snapshot wire format.
//
// The envelope carries a compressed ConfigPayload. All repeated string fields
// inside sub-messages are indices into a top-level StringTable rather than
// inline strings. The receiver expands indices back to strings in protoToRaw()
// before handing a RawConfig to compile(); compile() never sees proto types.
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/config/v1/snapshot.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadFormat int32

const (
	PayloadFormat_PAYLOAD_FORMAT_UNSPECIFIED PayloadFormat = 0
	PayloadFormat_PAYLOAD_FORMAT_PROTO       PayloadFormat = 1
	PayloadFormat_PAYLOAD_FORMAT_YAML        PayloadFormat = 2 // local/dev only
	PayloadFormat_PAYLOAD_FORMAT_JSON        PayloadFormat = 3 // local/dev only
	PayloadFormat_PAYLOAD_FORMAT_MSGPACK     PayloadFormat = 4 // optional; same logical shape as proto
)

// Enum value maps for PayloadFormat.
var (
	PayloadFormat_name = map[int32]string{
		0: "PAYLOAD_FORMAT_UNSPECIFIED",
		1: "PAYLOAD_FORMAT_PROTO",
		2: "PAYLOAD_FORMAT_YAML",
		3: "PAYLOAD_FORMAT_JSON",
		4: "PAYLOAD_FORMAT_MSGPACK",
	}
	PayloadFormat_value = map[string]int32{
		"PAYLOAD_FORMAT_UNSPECIFIED": 0,
		"PAYLOAD_FORMAT_PROTO":       1,
		"PAYLOAD_FORMAT_YAML":        2,
		"PAYLOAD_FORMAT_JSON":        3,
		"PAYLOAD_FORMAT_MSGPACK":     4,
	}
)

func (x PayloadFormat) Enum() *PayloadFormat {
	p := new(PayloadFormat)
	*p = x
	return p
}

func (x PayloadFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_orange_config_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (PayloadFormat) Type() protoreflect.EnumType {
	return &file_orange_config_v1_snapshot_proto_enumTypes[0]
}

func (x PayloadFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadFormat.Descriptor instead.
func (PayloadFormat) EnumDescriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0 // treated as COMPRESSION_NONE by protoToRaw()
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_ZSTD        Compression = 2
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_ZSTD",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_ZSTD":        2,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_orange_config_v1_snapshot_proto_enumTypes[1].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_orange_config_v1_snapshot_proto_enumTypes[1]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

type ProviderKind int32

const (
	ProviderKind_PROVIDER_KIND_UNSPECIFIED ProviderKind = 0
	ProviderKind_PROVIDER_KIND_ANTHROPIC   ProviderKind = 1
	ProviderKind_PROVIDER_KIND_OPENAI      ProviderKind = 2
	ProviderKind_PROVIDER_KIND_BEDROCK     ProviderKind = 3
)

// Enum value maps for ProviderKind.
var (
	ProviderKind_name = map[int32]string{
		0: "PROVIDER_KIND_UNSPECIFIED",
		1: "PROVIDER_KIND_ANTHROPIC",
		2: "PROVIDER_KIND_OPENAI",
		3: "PROVIDER_KIND_BEDROCK",
	}
	ProviderKind_value = map[string]int32{
		"PROVIDER_KIND_UNSPECIFIED": 0,
		"PROVIDER_KIND_ANTHROPIC":   1,
		"PROVIDER_KIND_OPENAI":      2,
		"PROVIDER_KIND_BEDROCK":     3,
	}
)

func (x ProviderKind) Enum() *ProviderKind {
	p := new(ProviderKind)
	*p = x
	return p
}

func (x ProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_orange_config_v1_snapshot_proto_enumTypes[2].Descriptor()
}

func (ProviderKind) Type() protoreflect.EnumType {
	return &file_orange_config_v1_snapshot_proto_enumTypes[2]
}

func (x ProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderKind.Descriptor instead.
func (ProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_BEARER      AuthType = 1
	AuthType_AUTH_TYPE_ANTHROPIC   AuthType = 2
	AuthType_AUTH_TYPE_GCP         AuthType = 3
	AuthType_AUTH_TYPE_AWS         AuthType = 4
	AuthType_AUTH_TYPE_GEMINI      AuthType = 5
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_BEARER",
		2: "AUTH_TYPE_ANTHROPIC",
		3: "AUTH_TYPE_GCP",
		4: "AUTH_TYPE_AWS",
		5: "AUTH_TYPE_GEMINI",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED": 0,
		"AUTH_TYPE_BEARER":      1,
		"AUTH_TYPE_ANTHROPIC":   2,
		"AUTH_TYPE_GCP":         3,
		"AUTH_TYPE_AWS":         4,
		"AUTH_TYPE_GEMINI":      5,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_orange_config_v1_snapshot_proto_enumTypes[3].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_orange_config_v1_snapshot_proto_enumTypes[3]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

// OnExceed controls the action taken when a rate limit is exhausted.
// UNSPECIFIED is treated as REJECT by protoToRaw().
type OnExceed int32

const (
	OnExceed_ON_EXCEED_UNSPECIFIED OnExceed = 0 // treated as ON_EXCEED_REJECT
	OnExceed_ON_EXCEED_REJECT      OnExceed = 1
	OnExceed_ON_EXCEED_THROTTLE    OnExceed = 2
	OnExceed_ON_EXCEED_LOG_ONLY    OnExceed = 3
)

// Enum value maps for OnExceed.
var (
	OnExceed_name = map[int32]string{
		0: "ON_EXCEED_UNSPECIFIED",
		1: "ON_EXCEED_REJECT",
		2: "ON_EXCEED_THROTTLE",
		3: "ON_EXCEED_LOG_ONLY",
	}
	OnExceed_value = map[string]int32{
		"ON_EXCEED_UNSPECIFIED": 0,
		"ON_EXCEED_REJECT":      1,
		"ON_EXCEED_THROTTLE":    2,
		"ON_EXCEED_LOG_ONLY":    3,
	}
)

func (x OnExceed) Enum() *OnExceed {
	p := new(OnExceed)
	*p = x
	return p
}

func (x OnExceed) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnExceed) Descriptor() protoreflect.EnumDescriptor {
	return file_orange_config_v1_snapshot_proto_enumTypes[4].Descriptor()
}

func (OnExceed) Type() protoreflect.EnumType {
	return &file_orange_config_v1_snapshot_proto_enumTypes[4]
}

func (x OnExceed) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnExceed.Descriptor instead.
func (OnExceed) EnumDescriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

// SnapshotEnvelope is the outermost frame delivered over gRPC or HTTP.
// Payload contains a compressed (or raw) ConfigPayload proto.
type SnapshotEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // monotonically increasing; receiver discards if <= last accepted
	Format        PayloadFormat          `protobuf:"varint,2,opt,name=format,proto3,enum=orange.config.v1.PayloadFormat" json:"format,omitempty"`
	Compression   Compression            `protobuf:"varint,3,opt,name=compression,proto3,enum=orange.config.v1.Compression" json:"compression,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // compressed ConfigPayload proto bytes
	Checksum      []byte                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA-256 of the decompressed payload bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnvelope) Reset() {
	*x = SnapshotEnvelope{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnvelope) ProtoMessage() {}

func (x *SnapshotEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnvelope.ProtoReflect.Descriptor instead.
func (*SnapshotEnvelope) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotEnvelope) GetFormat() PayloadFormat {
	if x != nil {
		return x.Format
	}
	return PayloadFormat_PAYLOAD_FORMAT_UNSPECIFIED
}

func (x *SnapshotEnvelope) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *SnapshotEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotEnvelope) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// ConfigPayload is the decompressed content of SnapshotEnvelope.payload.
// All repeated string fields in sub-messages are indices into strings.
// Records are sorted by their primary index before encoding to produce
// deterministic byte output for a given logical config.
type ConfigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       *StringTable           `protobuf:"bytes,1,opt,name=strings,proto3" json:"strings,omitempty"`
	Providers     []*Provider            `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`                     // sorted by name_idx
	Models        []*Model               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`                           // sorted by name_idx
	Servers       []*Server              `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`                         // sorted by name_idx
	Profiles      []*Profile             `protobuf:"bytes,5,rep,name=profiles,proto3" json:"profiles,omitempty"`                       // sorted by id_idx
	Keys          []*Key                 `protobuf:"bytes,6,rep,name=keys,proto3" json:"keys,omitempty"`                               // sorted by id_idx
	RateLimits    []*RateLimitScope      `protobuf:"bytes,7,rep,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"` // sorted by scope_idx; workspace/user scopes only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPayload) Reset() {
	*x = ConfigPayload{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPayload) ProtoMessage() {}

func (x *ConfigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPayload.ProtoReflect.Descriptor instead.
func (*ConfigPayload) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigPayload) GetStrings() *StringTable {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *ConfigPayload) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ConfigPayload) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ConfigPayload) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ConfigPayload) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ConfigPayload) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ConfigPayload) GetRateLimits() []*RateLimitScope {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

// StringTable deduplicates all repeated strings across the payload.
// Index 0 is reserved (empty / unset). The first real string is at index 1.
type StringTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringTable.ProtoReflect.Descriptor instead.
func (*StringTable) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *StringTable) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

type Provider struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NameIdx          uint32                 `protobuf:"varint,1,opt,name=name_idx,json=nameIdx,proto3" json:"name_idx,omitempty"` // llm.providers map key
	Kind             ProviderKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=orange.config.v1.ProviderKind" json:"kind,omitempty"`
	BackendSchemaIdx uint32                 `protobuf:"varint,3,opt,name=backend_schema_idx,json=backendSchemaIdx,proto3" json:"backend_schema_idx,omitempty"` // optional; 0 = unset (use kind as schema name)
	EndpointIdx      uint32                 `protobuf:"varint,4,opt,name=endpoint_idx,json=endpointIdx,proto3" json:"endpoint_idx,omitempty"`
	Auth             *Auth                  `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	Extra            []*KV                  `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty"` // forwarded headers / provider-specific params
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *Provider) GetNameIdx() uint32 {
	if x != nil {
		return x.NameIdx
	}
	return 0
}

func (x *Provider) GetKind() ProviderKind {
	if x != nil {
		return x.Kind
	}
	return ProviderKind_PROVIDER_KIND_UNSPECIFIED
}

func (x *Provider) GetBackendSchemaIdx() uint32 {
	if x != nil {
		return x.BackendSchemaIdx
	}
	return 0
}

func (x *Provider) GetEndpointIdx() uint32 {
	if x != nil {
		return x.EndpointIdx
	}
	return 0
}

func (x *Provider) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Provider) GetExtra() []*KV {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Model struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NameIdx           uint32                 `protobuf:"varint,1,opt,name=name_idx,json=nameIdx,proto3" json:"name_idx,omitempty"`             // client-facing model ID
	ProviderIdx       uint32                 `protobuf:"varint,2,opt,name=provider_idx,json=providerIdx,proto3" json:"provider_idx,omitempty"` // matches a Provider.name_idx
	ApiNameIdx        uint32                 `protobuf:"varint,3,opt,name=api_name_idx,json=apiNameIdx,proto3" json:"api_name_idx,omitempty"`  // backend model name; 0 = use name_idx
	EndpointOverrides []*EndpointOverride    `protobuf:"bytes,4,rep,name=endpoint_overrides,json=endpointOverrides,proto3" json:"endpoint_overrides,omitempty"`
	Pricing           *ModelPricing          `protobuf:"bytes,5,opt,name=pricing,proto3" json:"pricing,omitempty"`   // zero value = absent (no pricing)
	Metadata          *ModelMetadata         `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"` // zero value = absent
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *Model) GetNameIdx() uint32 {
	if x != nil {
		return x.NameIdx
	}
	return 0
}

func (x *Model) GetProviderIdx() uint32 {
	if x != nil {
		return x.ProviderIdx
	}
	return 0
}

func (x *Model) GetApiNameIdx() uint32 {
	if x != nil {
		return x.ApiNameIdx
	}
	return 0
}

func (x *Model) GetEndpointOverrides() []*EndpointOverride {
	if x != nil {
		return x.EndpointOverrides
	}
	return nil
}

func (x *Model) GetPricing() *ModelPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *Model) GetMetadata() *ModelMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EndpointOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationIdx  uint32                 `protobuf:"varint,1,opt,name=operation_idx,json=operationIdx,proto3" json:"operation_idx,omitempty"` // e.g. index of "chat_completions"
	ProviderIdx   uint32                 `protobuf:"varint,2,opt,name=provider_idx,json=providerIdx,proto3" json:"provider_idx,omitempty"`    // override provider for this operation only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointOverride) Reset() {
	*x = EndpointOverride{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointOverride) ProtoMessage() {}

func (x *EndpointOverride) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointOverride.ProtoReflect.Descriptor instead.
func (*EndpointOverride) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *EndpointOverride) GetOperationIdx() uint32 {
	if x != nil {
		return x.OperationIdx
	}
	return 0
}

func (x *EndpointOverride) GetProviderIdx() uint32 {
	if x != nil {
		return x.ProviderIdx
	}
	return 0
}

// ModelPricing holds per-model token prices in USD per million tokens.
// double is used on the wire; protoToRaw() converts to decimal.Decimal via
// decimal.NewFromFloat() before handing off to compile().
type ModelPricing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputMtok      float64                `protobuf:"fixed64,1,opt,name=input_mtok,json=inputMtok,proto3" json:"input_mtok,omitempty"`
	OutputMtok     float64                `protobuf:"fixed64,2,opt,name=output_mtok,json=outputMtok,proto3" json:"output_mtok,omitempty"`
	CacheReadMtok  float64                `protobuf:"fixed64,3,opt,name=cache_read_mtok,json=cacheReadMtok,proto3" json:"cache_read_mtok,omitempty"`
	CacheWriteMtok float64                `protobuf:"fixed64,4,opt,name=cache_write_mtok,json=cacheWriteMtok,proto3" json:"cache_write_mtok,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelPricing) Reset() {
	*x = ModelPricing{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPricing) ProtoMessage() {}

func (x *ModelPricing) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPricing.ProtoReflect.Descriptor instead.
func (*ModelPricing) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *ModelPricing) GetInputMtok() float64 {
	if x != nil {
		return x.InputMtok
	}
	return 0
}

func (x *ModelPricing) GetOutputMtok() float64 {
	if x != nil {
		return x.OutputMtok
	}
	return 0
}

func (x *ModelPricing) GetCacheReadMtok() float64 {
	if x != nil {
		return x.CacheReadMtok
	}
	return 0
}

func (x *ModelPricing) GetCacheWriteMtok() float64 {
	if x != nil {
		return x.CacheWriteMtok
	}
	return 0
}

type ModelMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DescriptionIdx uint32                 `protobuf:"varint,1,opt,name=description_idx,json=descriptionIdx,proto3" json:"description_idx,omitempty"`
	ContextLength  int32                  `protobuf:"varint,2,opt,name=context_length,json=contextLength,proto3" json:"context_length,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	TagIdxs        []uint32               `protobuf:"varint,4,rep,packed,name=tag_idxs,json=tagIdxs,proto3" json:"tag_idxs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelMetadata) Reset() {
	*x = ModelMetadata{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadata) ProtoMessage() {}

func (x *ModelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadata.ProtoReflect.Descriptor instead.
func (*ModelMetadata) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *ModelMetadata) GetDescriptionIdx() uint32 {
	if x != nil {
		return x.DescriptionIdx
	}
	return 0
}

func (x *ModelMetadata) GetContextLength() int32 {
	if x != nil {
		return x.ContextLength
	}
	return 0
}

func (x *ModelMetadata) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelMetadata) GetTagIdxs() []uint32 {
	if x != nil {
		return x.TagIdxs
	}
	return nil
}

type Server struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NameIdx          uint32                 `protobuf:"varint,1,opt,name=name_idx,json=nameIdx,proto3" json:"name_idx,omitempty"` // mcp.servers map key
	EndpointIdx      uint32                 `protobuf:"varint,2,opt,name=endpoint_idx,json=endpointIdx,proto3" json:"endpoint_idx,omitempty"`
	NamespaceIdx     uint32                 `protobuf:"varint,3,opt,name=namespace_idx,json=namespaceIdx,proto3" json:"namespace_idx,omitempty"`
	Auth             *Auth                  `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`                                                           // zero AuthType = absent
	ToolsIncludeIdxs []uint32               `protobuf:"varint,5,rep,packed,name=tools_include_idxs,json=toolsIncludeIdxs,proto3" json:"tools_include_idxs,omitempty"` // empty = all tools allowed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *Server) GetNameIdx() uint32 {
	if x != nil {
		return x.NameIdx
	}
	return 0
}

func (x *Server) GetEndpointIdx() uint32 {
	if x != nil {
		return x.EndpointIdx
	}
	return 0
}

func (x *Server) GetNamespaceIdx() uint32 {
	if x != nil {
		return x.NamespaceIdx
	}
	return 0
}

func (x *Server) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Server) GetToolsIncludeIdxs() []uint32 {
	if x != nil {
		return x.ToolsIncludeIdxs
	}
	return nil
}

// Auth carries an auth type enum and a string-table index for the secret
// reference. The reference (e.g. env://MY_VAR) is expanded by protoToRaw()
// and then resolved lazily at request time by the SecretResolver.
type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AuthType               `protobuf:"varint,1,opt,name=type,proto3,enum=orange.config.v1.AuthType" json:"type,omitempty"`
	SecretIdx     uint32                 `protobuf:"varint,2,opt,name=secret_idx,json=secretIdx,proto3" json:"secret_idx,omitempty"` // index of the secret ref string (env://, file://, literal://, …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *Auth) GetType() AuthType {
	if x != nil {
		return x.Type
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (x *Auth) GetSecretIdx() uint32 {
	if x != nil {
		return x.SecretIdx
	}
	return 0
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdIdx         uint32                 `protobuf:"varint,1,opt,name=id_idx,json=idIdx,proto3" json:"id_idx,omitempty"` // workspace/user/name identity
	Tools         []*ToolFilter          `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	AuthOverrides []*AuthOverride        `protobuf:"bytes,3,rep,name=auth_overrides,json=authOverrides,proto3" json:"auth_overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{10}
}

func (x *Profile) GetIdIdx() uint32 {
	if x != nil {
		return x.IdIdx
	}
	return 0
}

func (x *Profile) GetTools() []*ToolFilter {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Profile) GetAuthOverrides() []*AuthOverride {
	if x != nil {
		return x.AuthOverrides
	}
	return nil
}

type ToolFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIdx     uint32                 `protobuf:"varint,1,opt,name=server_idx,json=serverIdx,proto3" json:"server_idx,omitempty"`
	IncludeIdxs   []uint32               `protobuf:"varint,2,rep,packed,name=include_idxs,json=includeIdxs,proto3" json:"include_idxs,omitempty"` // empty = expose all tools the server allows
	Optional      bool                   `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFilter) Reset() {
	*x = ToolFilter{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFilter) ProtoMessage() {}

func (x *ToolFilter) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFilter.ProtoReflect.Descriptor instead.
func (*ToolFilter) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{11}
}

func (x *ToolFilter) GetServerIdx() uint32 {
	if x != nil {
		return x.ServerIdx
	}
	return 0
}

func (x *ToolFilter) GetIncludeIdxs() []uint32 {
	if x != nil {
		return x.IncludeIdxs
	}
	return nil
}

func (x *ToolFilter) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

type AuthOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIdx     uint32                 `protobuf:"varint,1,opt,name=server_idx,json=serverIdx,proto3" json:"server_idx,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOverride) Reset() {
	*x = AuthOverride{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOverride) ProtoMessage() {}

func (x *AuthOverride) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOverride.ProtoReflect.Descriptor instead.
func (*AuthOverride) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{12}
}

func (x *AuthOverride) GetServerIdx() uint32 {
	if x != nil {
		return x.ServerIdx
	}
	return 0
}

func (x *AuthOverride) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type Key struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdIdx            uint32                 `protobuf:"varint,1,opt,name=id_idx,json=idIdx,proto3" json:"id_idx,omitempty"` // workspace/user/name identity
	RoutingOverrides []*RoutingOverride     `protobuf:"bytes,2,rep,name=routing_overrides,json=routingOverrides,proto3" json:"routing_overrides,omitempty"`
	RateLimitRules   []*RateLimitRule       `protobuf:"bytes,3,rep,name=rate_limit_rules,json=rateLimitRules,proto3" json:"rate_limit_rules,omitempty"` // key-scope; set by the key owner
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{13}
}

func (x *Key) GetIdIdx() uint32 {
	if x != nil {
		return x.IdIdx
	}
	return 0
}

func (x *Key) GetRoutingOverrides() []*RoutingOverride {
	if x != nil {
		return x.RoutingOverrides
	}
	return nil
}

func (x *Key) GetRateLimitRules() []*RateLimitRule {
	if x != nil {
		return x.RateLimitRules
	}
	return nil
}

type RoutingOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelIdx      uint32                 `protobuf:"varint,1,opt,name=model_idx,json=modelIdx,proto3" json:"model_idx,omitempty"` // string-table index of the client-facing model ID
	Node          *RoutingNode           `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingOverride) Reset() {
	*x = RoutingOverride{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingOverride) ProtoMessage() {}

func (x *RoutingOverride) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingOverride.ProtoReflect.Descriptor instead.
func (*RoutingOverride) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{14}
}

func (x *RoutingOverride) GetModelIdx() uint32 {
	if x != nil {
		return x.ModelIdx
	}
	return 0
}

func (x *RoutingOverride) GetNode() *RoutingNode {
	if x != nil {
		return x.Node
	}
	return nil
}

// RoutingNode is a recursive tree node. Exactly one of target, chain, or split
// must be set. Nesting rules enforced by compile():
//   - chain children: target or split only (no chain-of-chain)
//   - split children: target or chain only (no split-of-split)
type RoutingNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RoutingNode_Target
	//	*RoutingNode_Chain
	//	*RoutingNode_Split
	Kind          isRoutingNode_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingNode) Reset() {
	*x = RoutingNode{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingNode) ProtoMessage() {}

func (x *RoutingNode) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingNode.ProtoReflect.Descriptor instead.
func (*RoutingNode) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{15}
}

func (x *RoutingNode) GetKind() isRoutingNode_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RoutingNode) GetTarget() *RoutingTarget {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Target); ok {
			return x.Target
		}
	}
	return nil
}

func (x *RoutingNode) GetChain() *ChainConfig {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Chain); ok {
			return x.Chain
		}
	}
	return nil
}

func (x *RoutingNode) GetSplit() *SplitConfig {
	if x != nil {
		if x, ok := x.Kind.(*RoutingNode_Split); ok {
			return x.Split
		}
	}
	return nil
}

type isRoutingNode_Kind interface {
	isRoutingNode_Kind()
}

type RoutingNode_Target struct {
	Target *RoutingTarget `protobuf:"bytes,1,opt,name=target,proto3,oneof"`
}

type RoutingNode_Chain struct {
	Chain *ChainConfig `protobuf:"bytes,2,opt,name=chain,proto3,oneof"`
}

type RoutingNode_Split struct {
	Split *SplitConfig `protobuf:"bytes,3,opt,name=split,proto3,oneof"`
}

func (*RoutingNode_Target) isRoutingNode_Kind() {}

func (*RoutingNode_Chain) isRoutingNode_Kind() {}

func (*RoutingNode_Split) isRoutingNode_Kind() {}

type RoutingTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderIdx   uint32                 `protobuf:"varint,1,opt,name=provider_idx,json=providerIdx,proto3" json:"provider_idx,omitempty"`
	NameIdx       uint32                 `protobuf:"varint,2,opt,name=name_idx,json=nameIdx,proto3" json:"name_idx,omitempty"` // backend model name; 0 = use client-facing model ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTarget) Reset() {
	*x = RoutingTarget{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTarget) ProtoMessage() {}

func (x *RoutingTarget) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTarget.ProtoReflect.Descriptor instead.
func (*RoutingTarget) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{16}
}

func (x *RoutingTarget) GetProviderIdx() uint32 {
	if x != nil {
		return x.ProviderIdx
	}
	return 0
}

func (x *RoutingTarget) GetNameIdx() uint32 {
	if x != nil {
		return x.NameIdx
	}
	return 0
}

type ChainConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retry         *RetryPolicy           `protobuf:"bytes,1,opt,name=retry,proto3" json:"retry,omitempty"` // optional
	Children      []*RoutingNode         `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainConfig) Reset() {
	*x = ChainConfig{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainConfig) ProtoMessage() {}

func (x *ChainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainConfig.ProtoReflect.Descriptor instead.
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{17}
}

func (x *ChainConfig) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *ChainConfig) GetChildren() []*RoutingNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type RetryPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RetryOnIdx      uint32                 `protobuf:"varint,1,opt,name=retry_on_idx,json=retryOnIdx,proto3" json:"retry_on_idx,omitempty"` // e.g. index of "connect-failure,reset,5xx"
	PerTryTimeoutMs int32                  `protobuf:"varint,2,opt,name=per_try_timeout_ms,json=perTryTimeoutMs,proto3" json:"per_try_timeout_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{18}
}

func (x *RetryPolicy) GetRetryOnIdx() uint32 {
	if x != nil {
		return x.RetryOnIdx
	}
	return 0
}

func (x *RetryPolicy) GetPerTryTimeoutMs() int32 {
	if x != nil {
		return x.PerTryTimeoutMs
	}
	return 0
}

type SplitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*SplitChild          `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"` // weights must sum to 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitConfig) Reset() {
	*x = SplitConfig{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitConfig) ProtoMessage() {}

func (x *SplitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitConfig.ProtoReflect.Descriptor instead.
func (*SplitConfig) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{19}
}

func (x *SplitConfig) GetChildren() []*SplitChild {
	if x != nil {
		return x.Children
	}
	return nil
}

type SplitChild struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        int32                  `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Node          *RoutingNode           `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitChild) Reset() {
	*x = SplitChild{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitChild) ProtoMessage() {}

func (x *SplitChild) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitChild.ProtoReflect.Descriptor instead.
func (*SplitChild) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{20}
}

func (x *SplitChild) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SplitChild) GetNode() *RoutingNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type RateLimitScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeIdx      uint32                 `protobuf:"varint,1,opt,name=scope_idx,json=scopeIdx,proto3" json:"scope_idx,omitempty"` // 1- or 2-segment scope (workspace or workspace/user)
	Rules         []*RateLimitRule       `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitScope) Reset() {
	*x = RateLimitScope{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitScope) ProtoMessage() {}

func (x *RateLimitScope) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitScope.ProtoReflect.Descriptor instead.
func (*RateLimitScope) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{21}
}

func (x *RateLimitScope) GetScopeIdx() uint32 {
	if x != nil {
		return x.ScopeIdx
	}
	return 0
}

func (x *RateLimitScope) GetRules() []*RateLimitRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// RateLimitRule mirrors RawRateLimitRule. USD fields use double on the wire;
// protoToRaw() converts them to decimal.Decimal via decimal.NewFromFloat().
// Zero values are unconstrained for that dimension.
// on_exceed defaults to ON_EXCEED_UNSPECIFIED which is treated as reject.
type RateLimitRule struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ModelIdxs               []uint32               `protobuf:"varint,1,rep,packed,name=model_idxs,json=modelIdxs,proto3" json:"model_idxs,omitempty"` // ["*"] encoded as the index of the literal "*" string
	UsdPerMinute            float64                `protobuf:"fixed64,2,opt,name=usd_per_minute,json=usdPerMinute,proto3" json:"usd_per_minute,omitempty"`
	UsdPerHour              float64                `protobuf:"fixed64,3,opt,name=usd_per_hour,json=usdPerHour,proto3" json:"usd_per_hour,omitempty"`
	UsdPerDay               float64                `protobuf:"fixed64,4,opt,name=usd_per_day,json=usdPerDay,proto3" json:"usd_per_day,omitempty"`
	Rpm                     int32                  `protobuf:"varint,5,opt,name=rpm,proto3" json:"rpm,omitempty"`
	Rph                     int32                  `protobuf:"varint,6,opt,name=rph,proto3" json:"rph,omitempty"`
	Rpd                     int32                  `protobuf:"varint,7,opt,name=rpd,proto3" json:"rpd,omitempty"`
	InputTokensPerMinute    int32                  `protobuf:"varint,8,opt,name=input_tokens_per_minute,json=inputTokensPerMinute,proto3" json:"input_tokens_per_minute,omitempty"`
	InputTokensPerHour      int32                  `protobuf:"varint,9,opt,name=input_tokens_per_hour,json=inputTokensPerHour,proto3" json:"input_tokens_per_hour,omitempty"`
	InputTokensPerDay       int32                  `protobuf:"varint,10,opt,name=input_tokens_per_day,json=inputTokensPerDay,proto3" json:"input_tokens_per_day,omitempty"`
	OutputTokensPerMinute   int32                  `protobuf:"varint,11,opt,name=output_tokens_per_minute,json=outputTokensPerMinute,proto3" json:"output_tokens_per_minute,omitempty"`
	OutputTokensPerHour     int32                  `protobuf:"varint,12,opt,name=output_tokens_per_hour,json=outputTokensPerHour,proto3" json:"output_tokens_per_hour,omitempty"`
	OutputTokensPerDay      int32                  `protobuf:"varint,13,opt,name=output_tokens_per_day,json=outputTokensPerDay,proto3" json:"output_tokens_per_day,omitempty"`
	CacheReadTokensPerHour  int32                  `protobuf:"varint,14,opt,name=cache_read_tokens_per_hour,json=cacheReadTokensPerHour,proto3" json:"cache_read_tokens_per_hour,omitempty"`
	CacheReadTokensPerDay   int32                  `protobuf:"varint,15,opt,name=cache_read_tokens_per_day,json=cacheReadTokensPerDay,proto3" json:"cache_read_tokens_per_day,omitempty"`
	CacheWriteTokensPerHour int32                  `protobuf:"varint,16,opt,name=cache_write_tokens_per_hour,json=cacheWriteTokensPerHour,proto3" json:"cache_write_tokens_per_hour,omitempty"`
	CacheWriteTokensPerDay  int32                  `protobuf:"varint,17,opt,name=cache_write_tokens_per_day,json=cacheWriteTokensPerDay,proto3" json:"cache_write_tokens_per_day,omitempty"`
	OnExceed                OnExceed               `protobuf:"varint,18,opt,name=on_exceed,json=onExceed,proto3,enum=orange.config.v1.OnExceed" json:"on_exceed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RateLimitRule) Reset() {
	*x = RateLimitRule{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRule) ProtoMessage() {}

func (x *RateLimitRule) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRule.ProtoReflect.Descriptor instead.
func (*RateLimitRule) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{22}
}

func (x *RateLimitRule) GetModelIdxs() []uint32 {
	if x != nil {
		return x.ModelIdxs
	}
	return nil
}

func (x *RateLimitRule) GetUsdPerMinute() float64 {
	if x != nil {
		return x.UsdPerMinute
	}
	return 0
}

func (x *RateLimitRule) GetUsdPerHour() float64 {
	if x != nil {
		return x.UsdPerHour
	}
	return 0
}

func (x *RateLimitRule) GetUsdPerDay() float64 {
	if x != nil {
		return x.UsdPerDay
	}
	return 0
}

func (x *RateLimitRule) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *RateLimitRule) GetRph() int32 {
	if x != nil {
		return x.Rph
	}
	return 0
}

func (x *RateLimitRule) GetRpd() int32 {
	if x != nil {
		return x.Rpd
	}
	return 0
}

func (x *RateLimitRule) GetInputTokensPerMinute() int32 {
	if x != nil {
		return x.InputTokensPerMinute
	}
	return 0
}

func (x *RateLimitRule) GetInputTokensPerHour() int32 {
	if x != nil {
		return x.InputTokensPerHour
	}
	return 0
}

func (x *RateLimitRule) GetInputTokensPerDay() int32 {
	if x != nil {
		return x.InputTokensPerDay
	}
	return 0
}

func (x *RateLimitRule) GetOutputTokensPerMinute() int32 {
	if x != nil {
		return x.OutputTokensPerMinute
	}
	return 0
}

func (x *RateLimitRule) GetOutputTokensPerHour() int32 {
	if x != nil {
		return x.OutputTokensPerHour
	}
	return 0
}

func (x *RateLimitRule) GetOutputTokensPerDay() int32 {
	if x != nil {
		return x.OutputTokensPerDay
	}
	return 0
}

func (x *RateLimitRule) GetCacheReadTokensPerHour() int32 {
	if x != nil {
		return x.CacheReadTokensPerHour
	}
	return 0
}

func (x *RateLimitRule) GetCacheReadTokensPerDay() int32 {
	if x != nil {
		return x.CacheReadTokensPerDay
	}
	return 0
}

func (x *RateLimitRule) GetCacheWriteTokensPerHour() int32 {
	if x != nil {
		return x.CacheWriteTokensPerHour
	}
	return 0
}

func (x *RateLimitRule) GetCacheWriteTokensPerDay() int32 {
	if x != nil {
		return x.CacheWriteTokensPerDay
	}
	return 0
}

func (x *RateLimitRule) GetOnExceed() OnExceed {
	if x != nil {
		return x.OnExceed
	}
	return OnExceed_ON_EXCEED_UNSPECIFIED
}

// KV is a key-value pair of string-table indices, used for provider extra fields.
type KV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIdx        uint32                 `protobuf:"varint,1,opt,name=key_idx,json=keyIdx,proto3" json:"key_idx,omitempty"`
	ValueIdx      uint32                 `protobuf:"varint,2,opt,name=value_idx,json=valueIdx,proto3" json:"value_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KV) Reset() {
	*x = KV{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{23}
}

func (x *KV) GetKeyIdx() uint32 {
	if x != nil {
		return x.KeyIdx
	}
	return 0
}

func (x *KV) GetValueIdx() uint32 {
	if x != nil {
		return x.ValueIdx
	}
	return 0
}

var File_orange_config_v1_snapshot_proto protoreflect.FileDescriptor

const file_orange_config_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1forange/config/v1/snapshot.proto\x12\x10orange.config.v1\"\xdc\x01\n" +
	"\x10SnapshotEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x127\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1f.orange.config.v1.PayloadFormatR\x06format\x12?\n" +
	"\vcompression\x18\x03 \x01(\x0e2\x1d.orange.config.v1.CompressionR\vcompression\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\fR\bchecksum\"\x8c\x03\n" +
	"\rConfigPayload\x127\n" +
	"\astrings\x18\x01 \x01(\v2\x1d.orange.config.v1.StringTableR\astrings\x128\n" +
	"\tproviders\x18\x02 \x03(\v2\x1a.orange.config.v1.ProviderR\tproviders\x12/\n" +
	"\x06models\x18\x03 \x03(\v2\x17.orange.config.v1.ModelR\x06models\x122\n" +
	"\aservers\x18\x04 \x03(\v2\x18.orange.config.v1.ServerR\aservers\x125\n" +
	"\bprofiles\x18\x05 \x03(\v2\x19.orange.config.v1.ProfileR\bprofiles\x12)\n" +
	"\x04keys\x18\x06 \x03(\v2\x15.orange.config.v1.KeyR\x04keys\x12A\n" +
	"\vrate_limits\x18\a \x03(\v2 .orange.config.v1.RateLimitScopeR\n" +
	"rateLimits\"'\n" +
	"\vStringTable\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\"\x82\x02\n" +
	"\bProvider\x12\x19\n" +
	"\bname_idx\x18\x01 \x01(\rR\anameIdx\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.orange.config.v1.ProviderKindR\x04kind\x12,\n" +
	"\x12backend_schema_idx\x18\x03 \x01(\rR\x10backendSchemaIdx\x12!\n" +
	"\fendpoint_idx\x18\x04 \x01(\rR\vendpointIdx\x12*\n" +
	"\x04auth\x18\x05 \x01(\v2\x16.orange.config.v1.AuthR\x04auth\x12*\n" +
	"\x05extra\x18\x06 \x03(\v2\x14.orange.config.v1.KVR\x05extra\"\xb1\x02\n" +
	"\x05Model\x12\x19\n" +
	"\bname_idx\x18\x01 \x01(\rR\anameIdx\x12!\n" +
	"\fprovider_idx\x18\x02 \x01(\rR\vproviderIdx\x12 \n" +
	"\fapi_name_idx\x18\x03 \x01(\rR\n" +
	"apiNameIdx\x12Q\n" +
	"\x12endpoint_overrides\x18\x04 \x03(\v2\".orange.config.v1.EndpointOverrideR\x11endpointOverrides\x128\n" +
	"\apricing\x18\x05 \x01(\v2\x1e.orange.config.v1.ModelPricingR\apricing\x12;\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1f.orange.config.v1.ModelMetadataR\bmetadata\"Z\n" +
	"\x10EndpointOverride\x12#\n" +
	"\roperation_idx\x18\x01 \x01(\rR\foperationIdx\x12!\n" +
	"\fprovider_idx\x18\x02 \x01(\rR\vproviderIdx\"\xa0\x01\n" +
	"\fModelPricing\x12\x1d\n" +
	"\n" +
	"input_mtok\x18\x01 \x01(\x01R\tinputMtok\x12\x1f\n" +
	"\voutput_mtok\x18\x02 \x01(\x01R\n" +
	"outputMtok\x12&\n" +
	"\x0fcache_read_mtok\x18\x03 \x01(\x01R\rcacheReadMtok\x12(\n" +
	"\x10cache_write_mtok\x18\x04 \x01(\x01R\x0ecacheWriteMtok\"\x99\x01\n" +
	"\rModelMetadata\x12'\n" +
	"\x0fdescription_idx\x18\x01 \x01(\rR\x0edescriptionIdx\x12%\n" +
	"\x0econtext_length\x18\x02 \x01(\x05R\rcontextLength\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12\x19\n" +
	"\btag_idxs\x18\x04 \x03(\rR\atagIdxs\"\xc5\x01\n" +
	"\x06Server\x12\x19\n" +
	"\bname_idx\x18\x01 \x01(\rR\anameIdx\x12!\n" +
	"\fendpoint_idx\x18\x02 \x01(\rR\vendpointIdx\x12#\n" +
	"\rnamespace_idx\x18\x03 \x01(\rR\fnamespaceIdx\x12*\n" +
	"\x04auth\x18\x04 \x01(\v2\x16.orange.config.v1.AuthR\x04auth\x12,\n" +
	"\x12tools_include_idxs\x18\x05 \x03(\rR\x10toolsIncludeIdxs\"U\n" +
	"\x04Auth\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.orange.config.v1.AuthTypeR\x04type\x12\x1d\n" +
	"\n" +
	"secret_idx\x18\x02 \x01(\rR\tsecretIdx\"\x9b\x01\n" +
	"\aProfile\x12\x15\n" +
	"\x06id_idx\x18\x01 \x01(\rR\x05idIdx\x122\n" +
	"\x05tools\x18\x02 \x03(\v2\x1c.orange.config.v1.ToolFilterR\x05tools\x12E\n" +
	"\x0eauth_overrides\x18\x03 \x03(\v2\x1e.orange.config.v1.AuthOverrideR\rauthOverrides\"j\n" +
	"\n" +
	"ToolFilter\x12\x1d\n" +
	"\n" +
	"server_idx\x18\x01 \x01(\rR\tserverIdx\x12!\n" +
	"\finclude_idxs\x18\x02 \x03(\rR\vincludeIdxs\x12\x1a\n" +
	"\boptional\x18\x03 \x01(\bR\boptional\"Y\n" +
	"\fAuthOverride\x12\x1d\n" +
	"\n" +
	"server_idx\x18\x01 \x01(\rR\tserverIdx\x12*\n" +
	"\x04auth\x18\x02 \x01(\v2\x16.orange.config.v1.AuthR\x04auth\"\xb7\x01\n" +
	"\x03Key\x12\x15\n" +
	"\x06id_idx\x18\x01 \x01(\rR\x05idIdx\x12N\n" +
	"\x11routing_overrides\x18\x02 \x03(\v2!.orange.config.v1.RoutingOverrideR\x10routingOverrides\x12I\n" +
	"\x10rate_limit_rules\x18\x03 \x03(\v2\x1f.orange.config.v1.RateLimitRuleR\x0erateLimitRules\"a\n" +
	"\x0fRoutingOverride\x12\x1b\n" +
	"\tmodel_idx\x18\x01 \x01(\rR\bmodelIdx\x121\n" +
	"\x04node\x18\x02 \x01(\v2\x1d.orange.config.v1.RoutingNodeR\x04node\"\xbe\x01\n" +
	"\vRoutingNode\x129\n" +
	"\x06target\x18\x01 \x01(\v2\x1f.orange.config.v1.RoutingTargetH\x00R\x06target\x125\n" +
	"\x05chain\x18\x02 \x01(\v2\x1d.orange.config.v1.ChainConfigH\x00R\x05chain\x125\n" +
	"\x05split\x18\x03 \x01(\v2\x1d.orange.config.v1.SplitConfigH\x00R\x05splitB\x06\n" +
	"\x04kind\"M\n" +
	"\rRoutingTarget\x12!\n" +
	"\fprovider_idx\x18\x01 \x01(\rR\vproviderIdx\x12\x19\n" +
	"\bname_idx\x18\x02 \x01(\rR\anameIdx\"}\n" +
	"\vChainConfig\x123\n" +
	"\x05retry\x18\x01 \x01(\v2\x1d.orange.config.v1.RetryPolicyR\x05retry\x129\n" +
	"\bchildren\x18\x02 \x03(\v2\x1d.orange.config.v1.RoutingNodeR\bchildren\"\\\n" +
	"\vRetryPolicy\x12 \n" +
	"\fretry_on_idx\x18\x01 \x01(\rR\n" +
	"retryOnIdx\x12+\n" +
	"\x12per_try_timeout_ms\x18\x02 \x01(\x05R\x0fperTryTimeoutMs\"G\n" +
	"\vSplitConfig\x128\n" +
	"\bchildren\x18\x01 \x03(\v2\x1c.orange.config.v1.SplitChildR\bchildren\"W\n" +
	"\n" +
	"SplitChild\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x05R\x06weight\x121\n" +
	"\x04node\x18\x02 \x01(\v2\x1d.orange.config.v1.RoutingNodeR\x04node\"d\n" +
	"\x0eRateLimitScope\x12\x1b\n" +
	"\tscope_idx\x18\x01 \x01(\rR\bscopeIdx\x125\n" +
	"\x05rules\x18\x02 \x03(\v2\x1f.orange.config.v1.RateLimitRuleR\x05rules\"\xb1\x06\n" +
	"\rRateLimitRule\x12\x1d\n" +
	"\n" +
	"model_idxs\x18\x01 \x03(\rR\tmodelIdxs\x12$\n" +
	"\x0eusd_per_minute\x18\x02 \x01(\x01R\fusdPerMinute\x12 \n" +
	"\fusd_per_hour\x18\x03 \x01(\x01R\n" +
	"usdPerHour\x12\x1e\n" +
	"\vusd_per_day\x18\x04 \x01(\x01R\tusdPerDay\x12\x10\n" +
	"\x03rpm\x18\x05 \x01(\x05R\x03rpm\x12\x10\n" +
	"\x03rph\x18\x06 \x01(\x05R\x03rph\x12\x10\n" +
	"\x03rpd\x18\a \x01(\x05R\x03rpd\x125\n" +
	"\x17input_tokens_per_minute\x18\b \x01(\x05R\x14inputTokensPerMinute\x121\n" +
	"\x15input_tokens_per_hour\x18\t \x01(\x05R\x12inputTokensPerHour\x12/\n" +
	"\x14input_tokens_per_day\x18\n" +
	" \x01(\x05R\x11inputTokensPerDay\x127\n" +
	"\x18output_tokens_per_minute\x18\v \x01(\x05R\x15outputTokensPerMinute\x123\n" +
	"\x16output_tokens_per_hour\x18\f \x01(\x05R\x13outputTokensPerHour\x121\n" +
	"\x15output_tokens_per_day\x18\r \x01(\x05R\x12outputTokensPerDay\x12:\n" +
	"\x1acache_read_tokens_per_hour\x18\x0e \x01(\x05R\x16cacheReadTokensPerHour\x128\n" +
	"\x19cache_read_tokens_per_day\x18\x0f \x01(\x05R\x15cacheReadTokensPerDay\x12<\n" +
	"\x1bcache_write_tokens_per_hour\x18\x10 \x01(\x05R\x17cacheWriteTokensPerHour\x12:\n" +
	"\x1acache_write_tokens_per_day\x18\x11 \x01(\x05R\x16cacheWriteTokensPerDay\x127\n" +
	"\ton_exceed\x18\x12 \x01(\x0e2\x1a.orange.config.v1.OnExceedR\bonExceed\":\n" +
	"\x02KV\x12\x17\n" +
	"\akey_idx\x18\x01 \x01(\rR\x06keyIdx\x12\x1b\n" +
	"\tvalue_idx\x18\x02 \x01(\rR\bvalueIdx*\x97\x01\n" +
	"\rPayloadFormat\x12\x1e\n" +
	"\x1aPAYLOAD_FORMAT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PAYLOAD_FORMAT_PROTO\x10\x01\x12\x17\n" +
	"\x13PAYLOAD_FORMAT_YAML\x10\x02\x12\x17\n" +
	"\x13PAYLOAD_FORMAT_JSON\x10\x03\x12\x1a\n" +
	"\x16PAYLOAD_FORMAT_MSGPACK\x10\x04*V\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x02*\x7f\n" +
	"\fProviderKind\x12\x1d\n" +
	"\x19PROVIDER_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROVIDER_KIND_ANTHROPIC\x10\x01\x12\x18\n" +
	"\x14PROVIDER_KIND_OPENAI\x10\x02\x12\x19\n" +
	"\x15PROVIDER_KIND_BEDROCK\x10\x03*\x90\x01\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AUTH_TYPE_BEARER\x10\x01\x12\x17\n" +
	"\x13AUTH_TYPE_ANTHROPIC\x10\x02\x12\x11\n" +
	"\rAUTH_TYPE_GCP\x10\x03\x12\x11\n" +
	"\rAUTH_TYPE_AWS\x10\x04\x12\x14\n" +
	"\x10AUTH_TYPE_GEMINI\x10\x05*k\n" +
	"\bOnExceed\x12\x19\n" +
	"\x15ON_EXCEED_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ON_EXCEED_REJECT\x10\x01\x12\x16\n" +
	"\x12ON_EXCEED_THROTTLE\x10\x02\x12\x16\n" +
	"\x12ON_EXCEED_LOG_ONLY\x10\x03B\xcd\x01\n" +
	"\x14com.orange.config.v1B\rSnapshotProtoP\x01ZDgithub.com/dio/transit/examples/orange/api/orange/config/v1;configv1\xa2\x02\x03OCX\xaa\x02\x10Orange.Config.V1\xca\x02\x10Orange\\Config\\V1\xe2\x02\x1cOrange\\Config\\V1\\GPBMetadata\xea\x02\x12Orange::Config::V1b\x06proto3"

var (
	file_orange_config_v1_snapshot_proto_rawDescOnce sync.Once
	file_orange_config_v1_snapshot_proto_rawDescData []byte
)

func file_orange_config_v1_snapshot_proto_rawDescGZIP() []byte {
	file_orange_config_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_orange_config_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)))
	})
	return file_orange_config_v1_snapshot_proto_rawDescData
}

var file_orange_config_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_orange_config_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_orange_config_v1_snapshot_proto_goTypes = []any{
	(PayloadFormat)(0),       // 0: orange.config.v1.PayloadFormat
	(Compression)(0),         // 1: orange.config.v1.Compression
	(ProviderKind)(0),        // 2: orange.config.v1.ProviderKind
	(AuthType)(0),            // 3: orange.config.v1.AuthType
	(OnExceed)(0),            // 4: orange.config.v1.OnExceed
	(*SnapshotEnvelope)(nil), // 5: orange.config.v1.SnapshotEnvelope
	(*ConfigPayload)(nil),    // 6: orange.config.v1.ConfigPayload
	(*StringTable)(nil),      // 7: orange.config.v1.StringTable
	(*Provider)(nil),         // 8: orange.config.v1.Provider
	(*Model)(nil),            // 9: orange.config.v1.Model
	(*EndpointOverride)(nil), // 10: orange.config.v1.EndpointOverride
	(*ModelPricing)(nil),     // 11: orange.config.v1.ModelPricing
	(*ModelMetadata)(nil),    // 12: orange.config.v1.ModelMetadata
	(*Server)(nil),           // 13: orange.config.v1.Server
	(*Auth)(nil),             // 14: orange.config.v1.Auth
	(*Profile)(nil),          // 15: orange.config.v1.Profile
	(*ToolFilter)(nil),       // 16: orange.config.v1.ToolFilter
	(*AuthOverride)(nil),     // 17: orange.config.v1.AuthOverride
	(*Key)(nil),              // 18: orange.config.v1.Key
	(*RoutingOverride)(nil),  // 19: orange.config.v1.RoutingOverride
	(*RoutingNode)(nil),      // 20: orange.config.v1.RoutingNode
	(*RoutingTarget)(nil),    // 21: orange.config.v1.RoutingTarget
	(*ChainConfig)(nil),      // 22: orange.config.v1.ChainConfig
	(*RetryPolicy)(nil),      // 23: orange.config.v1.RetryPolicy
	(*SplitConfig)(nil),      // 24: orange.config.v1.SplitConfig
	(*SplitChild)(nil),       // 25: orange.config.v1.SplitChild
	(*RateLimitScope)(nil),   // 26: orange.config.v1.RateLimitScope
	(*RateLimitRule)(nil),    // 27: orange.config.v1.RateLimitRule
	(*KV)(nil),               // 28: orange.config.v1.KV
}
var file_orange_config_v1_snapshot_proto_depIdxs = []int32{
	0,  // 0: orange.config.v1.SnapshotEnvelope.format:type_name -> orange.config.v1.PayloadFormat
	1,  // 1: orange.config.v1.SnapshotEnvelope.compression:type_name -> orange.config.v1.Compression
	7,  // 2: orange.config.v1.ConfigPayload.strings:type_name -> orange.config.v1.StringTable
	8,  // 3: orange.config.v1.ConfigPayload.providers:type_name -> orange.config.v1.Provider
	9,  // 4: orange.config.v1.ConfigPayload.models:type_name -> orange.config.v1.Model
	13, // 5: orange.config.v1.ConfigPayload.servers:type_name -> orange.config.v1.Server
	15, // 6: orange.config.v1.ConfigPayload.profiles:type_name -> orange.config.v1.Profile
	18, // 7: orange.config.v1.ConfigPayload.keys:type_name -> orange.config.v1.Key
	26, // 8: orange.config.v1.ConfigPayload.rate_limits:type_name -> orange.config.v1.RateLimitScope
	2,  // 9: orange.config.v1.Provider.kind:type_name -> orange.config.v1.ProviderKind
	14, // 10: orange.config.v1.Provider.auth:type_name -> orange.config.v1.Auth
	28, // 11: orange.config.v1.Provider.extra:type_name -> orange.config.v1.KV
	10, // 12: orange.config.v1.Model.endpoint_overrides:type_name -> orange.config.v1.EndpointOverride
	11, // 13: orange.config.v1.Model.pricing:type_name -> orange.config.v1.ModelPricing
	12, // 14: orange.config.v1.Model.metadata:type_name -> orange.config.v1.ModelMetadata
	14, // 15: orange.config.v1.Server.auth:type_name -> orange.config.v1.Auth
	3,  // 16: orange.config.v1.Auth.type:type_name -> orange.config.v1.AuthType
	16, // 17: orange.config.v1.Profile.tools:type_name -> orange.config.v1.ToolFilter
	17, // 18: orange.config.v1.Profile.auth_overrides:type_name -> orange.config.v1.AuthOverride
	14, // 19: orange.config.v1.AuthOverride.auth:type_name -> orange.config.v1.Auth
	19, // 20: orange.config.v1.Key.routing_overrides:type_name -> orange.config.v1.RoutingOverride
	27, // 21: orange.config.v1.Key.rate_limit_rules:type_name -> orange.config.v1.RateLimitRule
	20, // 22: orange.config.v1.RoutingOverride.node:type_name -> orange.config.v1.RoutingNode
	21, // 23: orange.config.v1.RoutingNode.target:type_name -> orange.config.v1.RoutingTarget
	22, // 24: orange.config.v1.RoutingNode.chain:type_name -> orange.config.v1.ChainConfig
	24, // 25: orange.config.v1.RoutingNode.split:type_name -> orange.config.v1.SplitConfig
	23, // 26: orange.config.v1.ChainConfig.retry:type_name -> orange.config.v1.RetryPolicy
	20, // 27: orange.config.v1.ChainConfig.children:type_name -> orange.config.v1.RoutingNode
	25, // 28: orange.config.v1.SplitConfig.children:type_name -> orange.config.v1.SplitChild
	20, // 29: orange.config.v1.SplitChild.node:type_name -> orange.config.v1.RoutingNode
	27, // 30: orange.config.v1.RateLimitScope.rules:type_name -> orange.config.v1.RateLimitRule
	4,  // 31: orange.config.v1.RateLimitRule.on_exceed:type_name -> orange.config.v1.OnExceed
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_orange_config_v1_snapshot_proto_init() }
func file_orange_config_v1_snapshot_proto_init() {
	if File_orange_config_v1_snapshot_proto != nil {
		return
	}
	file_orange_config_v1_snapshot_proto_msgTypes[15].OneofWrappers = []any{
		(*RoutingNode_Target)(nil),
		(*RoutingNode_Chain)(nil),
		(*RoutingNode_Split)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orange_config_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_orange_config_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_orange_config_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_orange_config_v1_snapshot_proto_msgTypes,
	}.Build()
	File_orange_config_v1_snapshot_proto = out.File
	file_orange_config_v1_snapshot_proto_goTypes = nil
	file_orange_config_v1_snapshot_proto_depIdxs = nil
}
