// Code generated by examples/orange/codemod; DO NOT EDIT.
// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package translator

import (
	"fmt"

	"github.com/dio/transit/examples/orange/internal/apischema/openai"

	"encoding/json"
)

// NewChatCompletionOpenAIToAzureOpenAITranslator implements [Factory] for OpenAI to Azure OpenAI translations.
// Except RequestBody method requires modification to satisfy Microsoft Azure OpenAI spec
// https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions, other interface methods
// are identical to NewChatCompletionOpenAIToOpenAITranslator's interface implementations.
// CODEMOD-TODO: original params were: apiVersion string, backendModel string
func NewChatCompletionOpenAIToAzureOpenAITranslator(cfg ProviderConfig) Translator {
	return &openAIToAzureOpenAITranslatorV1ChatCompletion{
		apiVersion: cfg.Extra["azure_api_version"],
		openAIToOpenAITranslatorV1ChatCompletion: openAIToOpenAITranslatorV1ChatCompletion{
			backendModel: cfg.BackendModel,
		},
	}
}

// openAIToAzureOpenAITranslatorV1ChatCompletion adapts OpenAI requests for Azure OpenAI Service.
// Azure ignores the model field in the request body, using deployment name from the URI path instead:
// https://learn.microsoft.com/en-us/azure/ai-foundry/openai/reference#chat-completions
type openAIToAzureOpenAITranslatorV1ChatCompletion struct {
	apiVersion string
	openAIToOpenAITranslatorV1ChatCompletion
}

func (o *openAIToAzureOpenAITranslatorV1ChatCompletion) RequestBody(raw []byte) (newHeaders []Header, newBody []byte, err error) {

	var req openai.ChatCompletionRequest
	_ = json.Unmarshal(raw, &req)
	modelName := req.Model
	if o.backendModel != "" {
		// If modelName is set we override the model to be used for the request.
		modelName = o.backendModel
	}
	// Ensure the response includes a model. This is set to accommodate test or
	// misimplemented backends.
	o.requestModel = modelName

	// Azure OpenAI uses a {deployment-id} that may match the deployed model's name.
	// We use the routed model as the deployment, stored in the path.
	pathTemplate := "/openai/deployments/%s/chat/completions?api-version=%s"
	newHeaders = []Header{{pathHeaderName, fmt.Sprintf(pathTemplate, modelName, o.apiVersion)}}
	if req.Stream {
		o.stream = true
	}

	// On retry, the path might have changed to a different provider. So, this will ensure that the path is always set to OpenAI.
	// CODEMOD-TODO: forceBodyMutation/flag handling removed; review if needed
	return
}

// RequestHeaders implements Translator.RequestHeaders.
func (o *openAIToAzureOpenAITranslatorV1ChatCompletion) RequestHeaders(_ map[string]string) ([]Header, error) {
	return nil, nil
}

func init() {
	Register("azureopenai", func(cfg ProviderConfig) Translator {
		return NewChatCompletionOpenAIToAzureOpenAITranslator(cfg)
	})
}
