// admin.proto — KeyAdminService: Key, PASETOToken, and KeySecret management.
//
// A Key is permanently bound to a single Workspace and a single User.
// key_format is always "paseto_v4.public" (Ed25519).
// key_id is server-assigned as a UUID7.
//
// PASETOToken records metadata and hash of an issued PASETO v4 token;
// the token itself is never stored.
//
// KeySecret (BYOK) is a user-supplied versioned upstream credential bound
// to a specific Key. It overrides the Workspace Secret during request dispatch.
//
// Authentication: every RPC requires AUTH_TYPE_API_KEY with scope "admin".
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/key/admin/v1/admin.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/dio/transit/examples/orange/api/orange/auth/v1"
	v1 "github.com/dio/transit/examples/orange/api/orange/routing/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKeyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoutingOverrides []*v1.RoutingOverride  `protobuf:"bytes,5,rep,name=routing_overrides,json=routingOverrides,proto3" json:"routing_overrides,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKeyRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKeyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateKeyRequest) GetRoutingOverrides() []*v1.RoutingOverride {
	if x != nil {
		return x.RoutingOverrides
	}
	return nil
}

type CreateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKeyResponse) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyResponse) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	PageToken     *string                `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListKeysRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListKeysRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *ListKeysRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListKeysRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListKeysResponse) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListKeysResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateKeyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Description      *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RoutingOverrides []*v1.RoutingOverride  `protobuf:"bytes,3,rep,name=routing_overrides,json=routingOverrides,proto3" json:"routing_overrides,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateKeyRequest) Reset() {
	*x = UpdateKeyRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyRequest) ProtoMessage() {}

func (x *UpdateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeyRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UpdateKeyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateKeyRequest) GetRoutingOverrides() []*v1.RoutingOverride {
	if x != nil {
		return x.RoutingOverrides
	}
	return nil
}

type UpdateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyResponse) Reset() {
	*x = UpdateKeyResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyResponse) ProtoMessage() {}

func (x *UpdateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeyResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateKeyResponse) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

// Key is permanently bound to a Workspace and User. key_format is always "paseto_v4.public".
type Key struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	KeyId       string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                   // UUID7, server-assigned
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"` // owning workspace; immutable
	UserId      string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // owning user; immutable
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                  // unique within workspace+user
	KeyFormat   string                 `protobuf:"bytes,5,opt,name=key_format,json=keyFormat,proto3" json:"key_format,omitempty"`       // always "paseto_v4.public"
	Description *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// routing_overrides maps client-facing model IDs to routing trees.
	// Empty means use default routing from GlobalConfig.Models.
	RoutingOverrides []*v1.RoutingOverride  `protobuf:"bytes,7,rep,name=routing_overrides,json=routingOverrides,proto3" json:"routing_overrides,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *Key) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Key) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Key) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetKeyFormat() string {
	if x != nil {
		return x.KeyFormat
	}
	return ""
}

func (x *Key) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Key) GetRoutingOverrides() []*v1.RoutingOverride {
	if x != nil {
		return x.RoutingOverrides
	}
	return nil
}

func (x *Key) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Key) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type IssueTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	KeyId string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// exp is the token expiry in seconds from now.
	TtlSeconds int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// pol is an optional embedded policy JSON attached to the token.
	Pol           *string `protobuf:"bytes,3,opt,name=pol,proto3,oneof" json:"pol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *IssueTokenRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *IssueTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *IssueTokenRequest) GetPol() string {
	if x != nil && x.Pol != nil {
		return *x.Pol
	}
	return ""
}

type IssueTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the signed PASETO v4 token — only returned once; not stored.
	Token         string       `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Metadata      *PASETOToken `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueTokenResponse) GetMetadata() *PASETOToken {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *PASETOToken           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetTokenResponse) GetToken() *PASETOToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type ListTokensRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyId          string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	IncludeRevoked *bool                  `protobuf:"varint,2,opt,name=include_revoked,json=includeRevoked,proto3,oneof" json:"include_revoked,omitempty"`
	Limit          *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	PageToken      *string                `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListTokensRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ListTokensRequest) GetIncludeRevoked() bool {
	if x != nil && x.IncludeRevoked != nil {
		return *x.IncludeRevoked
	}
	return false
}

func (x *ListTokensRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListTokensRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*PASETOToken         `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ListTokensResponse) GetTokens() []*PASETOToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

// PASETOToken stores token metadata only; the bearer token itself is never stored.
type PASETOToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"` // UUID7, server-assigned
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`       // owning key
	Jti           string                 `protobuf:"bytes,3,opt,name=jti,proto3" json:"jti,omitempty"`                        // JWT ID embedded in token
	Iat           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Pol           *string                `protobuf:"bytes,6,opt,name=pol,proto3,oneof" json:"pol,omitempty"`                        // embedded policy JSON
	TokenHash     string                 `protobuf:"bytes,7,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"` // SHA-256 of the raw token (hex)
	Revoked       bool                   `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PASETOToken) Reset() {
	*x = PASETOToken{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PASETOToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PASETOToken) ProtoMessage() {}

func (x *PASETOToken) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PASETOToken.ProtoReflect.Descriptor instead.
func (*PASETOToken) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *PASETOToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *PASETOToken) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PASETOToken) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *PASETOToken) GetIat() *timestamppb.Timestamp {
	if x != nil {
		return x.Iat
	}
	return nil
}

func (x *PASETOToken) GetExp() *timestamppb.Timestamp {
	if x != nil {
		return x.Exp
	}
	return nil
}

func (x *PASETOToken) GetPol() string {
	if x != nil && x.Pol != nil {
		return *x.Pol
	}
	return ""
}

func (x *PASETOToken) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *PASETOToken) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *PASETOToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateKeySecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	KeyId string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// upstream_target identifies the upstream (e.g. "openai", "anthropic").
	UpstreamTarget string `protobuf:"bytes,2,opt,name=upstream_target,json=upstreamTarget,proto3" json:"upstream_target,omitempty"`
	// value is the plaintext credential; stored encrypted, never returned.
	Value         string  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeySecretRequest) Reset() {
	*x = CreateKeySecretRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeySecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeySecretRequest) ProtoMessage() {}

func (x *CreateKeySecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeySecretRequest.ProtoReflect.Descriptor instead.
func (*CreateKeySecretRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *CreateKeySecretRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateKeySecretRequest) GetUpstreamTarget() string {
	if x != nil {
		return x.UpstreamTarget
	}
	return ""
}

func (x *CreateKeySecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateKeySecretRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateKeySecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *KeySecret             `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeySecretResponse) Reset() {
	*x = CreateKeySecretResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeySecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeySecretResponse) ProtoMessage() {}

func (x *CreateKeySecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeySecretResponse.ProtoReflect.Descriptor instead.
func (*CreateKeySecretResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *CreateKeySecretResponse) GetSecret() *KeySecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type GetKeySecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeySecretId   string                 `protobuf:"bytes,1,opt,name=key_secret_id,json=keySecretId,proto3" json:"key_secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeySecretRequest) Reset() {
	*x = GetKeySecretRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeySecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeySecretRequest) ProtoMessage() {}

func (x *GetKeySecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeySecretRequest.ProtoReflect.Descriptor instead.
func (*GetKeySecretRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetKeySecretRequest) GetKeySecretId() string {
	if x != nil {
		return x.KeySecretId
	}
	return ""
}

type GetKeySecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *KeySecret             `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeySecretResponse) Reset() {
	*x = GetKeySecretResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeySecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeySecretResponse) ProtoMessage() {}

func (x *GetKeySecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeySecretResponse.ProtoReflect.Descriptor instead.
func (*GetKeySecretResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *GetKeySecretResponse) GetSecret() *KeySecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ListKeySecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	PageToken     *string                `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeySecretsRequest) Reset() {
	*x = ListKeySecretsRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeySecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeySecretsRequest) ProtoMessage() {}

func (x *ListKeySecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeySecretsRequest.ProtoReflect.Descriptor instead.
func (*ListKeySecretsRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ListKeySecretsRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ListKeySecretsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListKeySecretsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListKeySecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*KeySecret           `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeySecretsResponse) Reset() {
	*x = ListKeySecretsResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeySecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeySecretsResponse) ProtoMessage() {}

func (x *ListKeySecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeySecretsResponse.ProtoReflect.Descriptor instead.
func (*ListKeySecretsResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListKeySecretsResponse) GetSecrets() []*KeySecret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ListKeySecretsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RotateKeySecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeySecretId   string                 `protobuf:"bytes,1,opt,name=key_secret_id,json=keySecretId,proto3" json:"key_secret_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeySecretRequest) Reset() {
	*x = RotateKeySecretRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeySecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeySecretRequest) ProtoMessage() {}

func (x *RotateKeySecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeySecretRequest.ProtoReflect.Descriptor instead.
func (*RotateKeySecretRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *RotateKeySecretRequest) GetKeySecretId() string {
	if x != nil {
		return x.KeySecretId
	}
	return ""
}

func (x *RotateKeySecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RotateKeySecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *KeySecret             `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeySecretResponse) Reset() {
	*x = RotateKeySecretResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeySecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeySecretResponse) ProtoMessage() {}

func (x *RotateKeySecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeySecretResponse.ProtoReflect.Descriptor instead.
func (*RotateKeySecretResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *RotateKeySecretResponse) GetSecret() *KeySecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type DeleteKeySecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeySecretId   string                 `protobuf:"bytes,1,opt,name=key_secret_id,json=keySecretId,proto3" json:"key_secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeySecretRequest) Reset() {
	*x = DeleteKeySecretRequest{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeySecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeySecretRequest) ProtoMessage() {}

func (x *DeleteKeySecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeySecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeySecretRequest) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteKeySecretRequest) GetKeySecretId() string {
	if x != nil {
		return x.KeySecretId
	}
	return ""
}

type DeleteKeySecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeySecretResponse) Reset() {
	*x = DeleteKeySecretResponse{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeySecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeySecretResponse) ProtoMessage() {}

func (x *DeleteKeySecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeySecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeySecretResponse) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

// KeySecret is a versioned upstream credential bound to a Key (BYOK).
// Overrides Workspace Secret during request dispatch for the same upstream_target.
type KeySecret struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeySecretId    string                 `protobuf:"bytes,1,opt,name=key_secret_id,json=keySecretId,proto3" json:"key_secret_id,omitempty"`        // UUID7, server-assigned
	KeyId          string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                            // owning key; immutable
	UpstreamTarget string                 `protobuf:"bytes,3,opt,name=upstream_target,json=upstreamTarget,proto3" json:"upstream_target,omitempty"` // e.g. "openai"
	Version        int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                                    // increments on rotate
	Active         bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Description    *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeySecret) Reset() {
	*x = KeySecret{}
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySecret) ProtoMessage() {}

func (x *KeySecret) ProtoReflect() protoreflect.Message {
	mi := &file_orange_key_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySecret.ProtoReflect.Descriptor instead.
func (*KeySecret) Descriptor() ([]byte, []int) {
	return file_orange_key_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *KeySecret) GetKeySecretId() string {
	if x != nil {
		return x.KeySecretId
	}
	return ""
}

func (x *KeySecret) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeySecret) GetUpstreamTarget() string {
	if x != nil {
		return x.UpstreamTarget
	}
	return ""
}

func (x *KeySecret) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeySecret) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *KeySecret) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *KeySecret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeySecret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_orange_key_admin_v1_admin_proto protoreflect.FileDescriptor

const file_orange_key_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1forange/key/admin/v1/admin.proto\x12\x13orange.key.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!orange/auth/v1/auth_options.proto\x1a\x1forange/routing/v1/routing.proto\"\xb3\x02\n" +
	"\x10CreateKeyRequest\x12,\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\vworkspaceId\x12\"\n" +
	"\auser_id\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x06userId\x12;\n" +
	"\x04name\x18\x03 \x01(\tB'\xbaH$r\"\x10\x02\x18?2\x1c^[a-z0-9][a-z0-9-]*[a-z0-9]$R\x04name\x12/\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\vdescription\x88\x01\x01\x12O\n" +
	"\x11routing_overrides\x18\x05 \x03(\v2\".orange.routing.v1.RoutingOverrideR\x10routingOverridesB\x0e\n" +
	"\f_description\"?\n" +
	"\x11CreateKeyResponse\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.orange.key.admin.v1.KeyR\x03key\"1\n" +
	"\rGetKeyRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\"<\n" +
	"\x0eGetKeyResponse\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.orange.key.admin.v1.KeyR\x03key\"\xd8\x01\n" +
	"\x0fListKeysRequest\x12,\n" +
	"\fworkspace_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\vworkspaceId\x12'\n" +
	"\auser_id\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$H\x00R\x06userId\x88\x01\x01\x12%\n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00H\x01R\x05limit\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x02R\tpageToken\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\b\n" +
	"\x06_limitB\r\n" +
	"\v_page_token\"h\n" +
	"\x10ListKeysResponse\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.orange.key.admin.v1.KeyR\x04keys\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc6\x01\n" +
	"\x10UpdateKeyRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\x12/\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\vdescription\x88\x01\x01\x12O\n" +
	"\x11routing_overrides\x18\x03 \x03(\v2\".orange.routing.v1.RoutingOverrideR\x10routingOverridesB\x0e\n" +
	"\f_description\"?\n" +
	"\x11UpdateKeyResponse\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.orange.key.admin.v1.KeyR\x03key\"4\n" +
	"\x10DeleteKeyRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\"\x13\n" +
	"\x11DeleteKeyResponse\"\x89\x03\n" +
	"\x03Key\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"key_format\x18\x05 \x01(\tR\tkeyFormat\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x12O\n" +
	"\x11routing_overrides\x18\a \x03(\v2\".orange.routing.v1.RoutingOverrideR\x10routingOverrides\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_description\"\x8c\x01\n" +
	"\x11IssueTokenRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\x12,\n" +
	"\vttl_seconds\x18\x02 \x01(\x03B\v\xbaH\b\"\x06\x18\x80\xa3\x05(\x01R\n" +
	"ttlSeconds\x12\x1f\n" +
	"\x03pol\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 H\x00R\x03pol\x88\x01\x01B\x06\n" +
	"\x04_pol\"h\n" +
	"\x12IssueTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12<\n" +
	"\bmetadata\x18\x02 \x01(\v2 .orange.key.admin.v1.PASETOTokenR\bmetadata\"7\n" +
	"\x0fGetTokenRequest\x12$\n" +
	"\btoken_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\atokenId\"J\n" +
	"\x10GetTokenResponse\x126\n" +
	"\x05token\x18\x01 \x01(\v2 .orange.key.admin.v1.PASETOTokenR\x05token\"\xdb\x01\n" +
	"\x11ListTokensRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\x12,\n" +
	"\x0finclude_revoked\x18\x02 \x01(\bH\x00R\x0eincludeRevoked\x88\x01\x01\x12%\n" +
	"\x05limit\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00H\x01R\x05limit\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x02R\tpageToken\x88\x01\x01B\x12\n" +
	"\x10_include_revokedB\b\n" +
	"\x06_limitB\r\n" +
	"\v_page_token\"v\n" +
	"\x12ListTokensResponse\x128\n" +
	"\x06tokens\x18\x01 \x03(\v2 .orange.key.admin.v1.PASETOTokenR\x06tokens\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\":\n" +
	"\x12RevokeTokenRequest\x12$\n" +
	"\btoken_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\atokenId\"\x15\n" +
	"\x13RevokeTokenResponse\"\xc0\x02\n" +
	"\vPASETOToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03jti\x18\x03 \x01(\tR\x03jti\x12,\n" +
	"\x03iat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03iat\x12,\n" +
	"\x03exp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03exp\x12\x15\n" +
	"\x03pol\x18\x06 \x01(\tH\x00R\x03pol\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"token_hash\x18\a \x01(\tR\ttokenHash\x12\x18\n" +
	"\arevoked\x18\b \x01(\bR\arevoked\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x06\n" +
	"\x04_pol\"\xd2\x01\n" +
	"\x16CreateKeySecretRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\x123\n" +
	"\x0fupstream_target\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x0eupstreamTarget\x12 \n" +
	"\x05value\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80@R\x05value\x12/\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"Q\n" +
	"\x17CreateKeySecretResponse\x126\n" +
	"\x06secret\x18\x01 \x01(\v2\x1e.orange.key.admin.v1.KeySecretR\x06secret\"D\n" +
	"\x13GetKeySecretRequest\x12-\n" +
	"\rkey_secret_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\vkeySecretId\"N\n" +
	"\x14GetKeySecretResponse\x126\n" +
	"\x06secret\x18\x01 \x01(\v2\x1e.orange.key.admin.v1.KeySecretR\x06secret\"\x9d\x01\n" +
	"\x15ListKeySecretsRequest\x12 \n" +
	"\x06key_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\x05keyId\x12%\n" +
	"\x05limit\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00H\x00R\x05limit\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tH\x01R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_limitB\r\n" +
	"\v_page_token\"z\n" +
	"\x16ListKeySecretsResponse\x128\n" +
	"\asecrets\x18\x01 \x03(\v2\x1e.orange.key.admin.v1.KeySecretR\asecrets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"i\n" +
	"\x16RotateKeySecretRequest\x12-\n" +
	"\rkey_secret_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\vkeySecretId\x12 \n" +
	"\x05value\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80@R\x05value\"Q\n" +
	"\x17RotateKeySecretResponse\x126\n" +
	"\x06secret\x18\x01 \x01(\v2\x1e.orange.key.admin.v1.KeySecretR\x06secret\"G\n" +
	"\x16DeleteKeySecretRequest\x12-\n" +
	"\rkey_secret_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18$R\vkeySecretId\"\x19\n" +
	"\x17DeleteKeySecretResponse\"\xce\x02\n" +
	"\tKeySecret\x12\"\n" +
	"\rkey_secret_id\x18\x01 \x01(\tR\vkeySecretId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12'\n" +
	"\x0fupstream_target\x18\x03 \x01(\tR\x0eupstreamTarget\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_description2\xd6\f\n" +
	"\x0fKeyAdminService\x12j\n" +
	"\tCreateKey\x12%.orange.key.admin.v1.CreateKeyRequest\x1a&.orange.key.admin.v1.CreateKeyResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12d\n" +
	"\x06GetKey\x12\".orange.key.admin.v1.GetKeyRequest\x1a#.orange.key.admin.v1.GetKeyResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12j\n" +
	"\bListKeys\x12$.orange.key.admin.v1.ListKeysRequest\x1a%.orange.key.admin.v1.ListKeysResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12j\n" +
	"\tUpdateKey\x12%.orange.key.admin.v1.UpdateKeyRequest\x1a&.orange.key.admin.v1.UpdateKeyResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12j\n" +
	"\tDeleteKey\x12%.orange.key.admin.v1.DeleteKeyRequest\x1a&.orange.key.admin.v1.DeleteKeyResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12m\n" +
	"\n" +
	"IssueToken\x12&.orange.key.admin.v1.IssueTokenRequest\x1a'.orange.key.admin.v1.IssueTokenResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12j\n" +
	"\bGetToken\x12$.orange.key.admin.v1.GetTokenRequest\x1a%.orange.key.admin.v1.GetTokenResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12p\n" +
	"\n" +
	"ListTokens\x12&.orange.key.admin.v1.ListTokensRequest\x1a'.orange.key.admin.v1.ListTokensResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12p\n" +
	"\vRevokeToken\x12'.orange.key.admin.v1.RevokeTokenRequest\x1a(.orange.key.admin.v1.RevokeTokenResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12|\n" +
	"\x0fCreateKeySecret\x12+.orange.key.admin.v1.CreateKeySecretRequest\x1a,.orange.key.admin.v1.CreateKeySecretResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12v\n" +
	"\fGetKeySecret\x12(.orange.key.admin.v1.GetKeySecretRequest\x1a).orange.key.admin.v1.GetKeySecretResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12|\n" +
	"\x0eListKeySecrets\x12*.orange.key.admin.v1.ListKeySecretsRequest\x1a+.orange.key.admin.v1.ListKeySecretsResponse\"\x11\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x90\x02\x01\x12|\n" +
	"\x0fRotateKeySecret\x12+.orange.key.admin.v1.RotateKeySecretRequest\x1a,.orange.key.admin.v1.RotateKeySecretResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05admin\x12|\n" +
	"\x0fDeleteKeySecret\x12+.orange.key.admin.v1.DeleteKeySecretRequest\x1a,.orange.key.admin.v1.DeleteKeySecretResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05adminB\xdc\x01\n" +
	"\x17com.orange.key.admin.v1B\n" +
	"AdminProtoP\x01ZFgithub.com/dio/transit/examples/orange/api/orange/key/admin/v1;adminv1\xa2\x02\x03OKA\xaa\x02\x13Orange.Key.Admin.V1\xca\x02\x13Orange\\Key\\Admin\\V1\xe2\x02\x1fOrange\\Key\\Admin\\V1\\GPBMetadata\xea\x02\x16Orange::Key::Admin::V1b\x06proto3"

var (
	file_orange_key_admin_v1_admin_proto_rawDescOnce sync.Once
	file_orange_key_admin_v1_admin_proto_rawDescData []byte
)

func file_orange_key_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_orange_key_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_orange_key_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_key_admin_v1_admin_proto_rawDesc), len(file_orange_key_admin_v1_admin_proto_rawDesc)))
	})
	return file_orange_key_admin_v1_admin_proto_rawDescData
}

var file_orange_key_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_orange_key_admin_v1_admin_proto_goTypes = []any{
	(*CreateKeyRequest)(nil),        // 0: orange.key.admin.v1.CreateKeyRequest
	(*CreateKeyResponse)(nil),       // 1: orange.key.admin.v1.CreateKeyResponse
	(*GetKeyRequest)(nil),           // 2: orange.key.admin.v1.GetKeyRequest
	(*GetKeyResponse)(nil),          // 3: orange.key.admin.v1.GetKeyResponse
	(*ListKeysRequest)(nil),         // 4: orange.key.admin.v1.ListKeysRequest
	(*ListKeysResponse)(nil),        // 5: orange.key.admin.v1.ListKeysResponse
	(*UpdateKeyRequest)(nil),        // 6: orange.key.admin.v1.UpdateKeyRequest
	(*UpdateKeyResponse)(nil),       // 7: orange.key.admin.v1.UpdateKeyResponse
	(*DeleteKeyRequest)(nil),        // 8: orange.key.admin.v1.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),       // 9: orange.key.admin.v1.DeleteKeyResponse
	(*Key)(nil),                     // 10: orange.key.admin.v1.Key
	(*IssueTokenRequest)(nil),       // 11: orange.key.admin.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),      // 12: orange.key.admin.v1.IssueTokenResponse
	(*GetTokenRequest)(nil),         // 13: orange.key.admin.v1.GetTokenRequest
	(*GetTokenResponse)(nil),        // 14: orange.key.admin.v1.GetTokenResponse
	(*ListTokensRequest)(nil),       // 15: orange.key.admin.v1.ListTokensRequest
	(*ListTokensResponse)(nil),      // 16: orange.key.admin.v1.ListTokensResponse
	(*RevokeTokenRequest)(nil),      // 17: orange.key.admin.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),     // 18: orange.key.admin.v1.RevokeTokenResponse
	(*PASETOToken)(nil),             // 19: orange.key.admin.v1.PASETOToken
	(*CreateKeySecretRequest)(nil),  // 20: orange.key.admin.v1.CreateKeySecretRequest
	(*CreateKeySecretResponse)(nil), // 21: orange.key.admin.v1.CreateKeySecretResponse
	(*GetKeySecretRequest)(nil),     // 22: orange.key.admin.v1.GetKeySecretRequest
	(*GetKeySecretResponse)(nil),    // 23: orange.key.admin.v1.GetKeySecretResponse
	(*ListKeySecretsRequest)(nil),   // 24: orange.key.admin.v1.ListKeySecretsRequest
	(*ListKeySecretsResponse)(nil),  // 25: orange.key.admin.v1.ListKeySecretsResponse
	(*RotateKeySecretRequest)(nil),  // 26: orange.key.admin.v1.RotateKeySecretRequest
	(*RotateKeySecretResponse)(nil), // 27: orange.key.admin.v1.RotateKeySecretResponse
	(*DeleteKeySecretRequest)(nil),  // 28: orange.key.admin.v1.DeleteKeySecretRequest
	(*DeleteKeySecretResponse)(nil), // 29: orange.key.admin.v1.DeleteKeySecretResponse
	(*KeySecret)(nil),               // 30: orange.key.admin.v1.KeySecret
	(*v1.RoutingOverride)(nil),      // 31: orange.routing.v1.RoutingOverride
	(*timestamppb.Timestamp)(nil),   // 32: google.protobuf.Timestamp
}
var file_orange_key_admin_v1_admin_proto_depIdxs = []int32{
	31, // 0: orange.key.admin.v1.CreateKeyRequest.routing_overrides:type_name -> orange.routing.v1.RoutingOverride
	10, // 1: orange.key.admin.v1.CreateKeyResponse.key:type_name -> orange.key.admin.v1.Key
	10, // 2: orange.key.admin.v1.GetKeyResponse.key:type_name -> orange.key.admin.v1.Key
	10, // 3: orange.key.admin.v1.ListKeysResponse.keys:type_name -> orange.key.admin.v1.Key
	31, // 4: orange.key.admin.v1.UpdateKeyRequest.routing_overrides:type_name -> orange.routing.v1.RoutingOverride
	10, // 5: orange.key.admin.v1.UpdateKeyResponse.key:type_name -> orange.key.admin.v1.Key
	31, // 6: orange.key.admin.v1.Key.routing_overrides:type_name -> orange.routing.v1.RoutingOverride
	32, // 7: orange.key.admin.v1.Key.created_at:type_name -> google.protobuf.Timestamp
	32, // 8: orange.key.admin.v1.Key.updated_at:type_name -> google.protobuf.Timestamp
	19, // 9: orange.key.admin.v1.IssueTokenResponse.metadata:type_name -> orange.key.admin.v1.PASETOToken
	19, // 10: orange.key.admin.v1.GetTokenResponse.token:type_name -> orange.key.admin.v1.PASETOToken
	19, // 11: orange.key.admin.v1.ListTokensResponse.tokens:type_name -> orange.key.admin.v1.PASETOToken
	32, // 12: orange.key.admin.v1.PASETOToken.iat:type_name -> google.protobuf.Timestamp
	32, // 13: orange.key.admin.v1.PASETOToken.exp:type_name -> google.protobuf.Timestamp
	32, // 14: orange.key.admin.v1.PASETOToken.created_at:type_name -> google.protobuf.Timestamp
	30, // 15: orange.key.admin.v1.CreateKeySecretResponse.secret:type_name -> orange.key.admin.v1.KeySecret
	30, // 16: orange.key.admin.v1.GetKeySecretResponse.secret:type_name -> orange.key.admin.v1.KeySecret
	30, // 17: orange.key.admin.v1.ListKeySecretsResponse.secrets:type_name -> orange.key.admin.v1.KeySecret
	30, // 18: orange.key.admin.v1.RotateKeySecretResponse.secret:type_name -> orange.key.admin.v1.KeySecret
	32, // 19: orange.key.admin.v1.KeySecret.created_at:type_name -> google.protobuf.Timestamp
	32, // 20: orange.key.admin.v1.KeySecret.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 21: orange.key.admin.v1.KeyAdminService.CreateKey:input_type -> orange.key.admin.v1.CreateKeyRequest
	2,  // 22: orange.key.admin.v1.KeyAdminService.GetKey:input_type -> orange.key.admin.v1.GetKeyRequest
	4,  // 23: orange.key.admin.v1.KeyAdminService.ListKeys:input_type -> orange.key.admin.v1.ListKeysRequest
	6,  // 24: orange.key.admin.v1.KeyAdminService.UpdateKey:input_type -> orange.key.admin.v1.UpdateKeyRequest
	8,  // 25: orange.key.admin.v1.KeyAdminService.DeleteKey:input_type -> orange.key.admin.v1.DeleteKeyRequest
	11, // 26: orange.key.admin.v1.KeyAdminService.IssueToken:input_type -> orange.key.admin.v1.IssueTokenRequest
	13, // 27: orange.key.admin.v1.KeyAdminService.GetToken:input_type -> orange.key.admin.v1.GetTokenRequest
	15, // 28: orange.key.admin.v1.KeyAdminService.ListTokens:input_type -> orange.key.admin.v1.ListTokensRequest
	17, // 29: orange.key.admin.v1.KeyAdminService.RevokeToken:input_type -> orange.key.admin.v1.RevokeTokenRequest
	20, // 30: orange.key.admin.v1.KeyAdminService.CreateKeySecret:input_type -> orange.key.admin.v1.CreateKeySecretRequest
	22, // 31: orange.key.admin.v1.KeyAdminService.GetKeySecret:input_type -> orange.key.admin.v1.GetKeySecretRequest
	24, // 32: orange.key.admin.v1.KeyAdminService.ListKeySecrets:input_type -> orange.key.admin.v1.ListKeySecretsRequest
	26, // 33: orange.key.admin.v1.KeyAdminService.RotateKeySecret:input_type -> orange.key.admin.v1.RotateKeySecretRequest
	28, // 34: orange.key.admin.v1.KeyAdminService.DeleteKeySecret:input_type -> orange.key.admin.v1.DeleteKeySecretRequest
	1,  // 35: orange.key.admin.v1.KeyAdminService.CreateKey:output_type -> orange.key.admin.v1.CreateKeyResponse
	3,  // 36: orange.key.admin.v1.KeyAdminService.GetKey:output_type -> orange.key.admin.v1.GetKeyResponse
	5,  // 37: orange.key.admin.v1.KeyAdminService.ListKeys:output_type -> orange.key.admin.v1.ListKeysResponse
	7,  // 38: orange.key.admin.v1.KeyAdminService.UpdateKey:output_type -> orange.key.admin.v1.UpdateKeyResponse
	9,  // 39: orange.key.admin.v1.KeyAdminService.DeleteKey:output_type -> orange.key.admin.v1.DeleteKeyResponse
	12, // 40: orange.key.admin.v1.KeyAdminService.IssueToken:output_type -> orange.key.admin.v1.IssueTokenResponse
	14, // 41: orange.key.admin.v1.KeyAdminService.GetToken:output_type -> orange.key.admin.v1.GetTokenResponse
	16, // 42: orange.key.admin.v1.KeyAdminService.ListTokens:output_type -> orange.key.admin.v1.ListTokensResponse
	18, // 43: orange.key.admin.v1.KeyAdminService.RevokeToken:output_type -> orange.key.admin.v1.RevokeTokenResponse
	21, // 44: orange.key.admin.v1.KeyAdminService.CreateKeySecret:output_type -> orange.key.admin.v1.CreateKeySecretResponse
	23, // 45: orange.key.admin.v1.KeyAdminService.GetKeySecret:output_type -> orange.key.admin.v1.GetKeySecretResponse
	25, // 46: orange.key.admin.v1.KeyAdminService.ListKeySecrets:output_type -> orange.key.admin.v1.ListKeySecretsResponse
	27, // 47: orange.key.admin.v1.KeyAdminService.RotateKeySecret:output_type -> orange.key.admin.v1.RotateKeySecretResponse
	29, // 48: orange.key.admin.v1.KeyAdminService.DeleteKeySecret:output_type -> orange.key.admin.v1.DeleteKeySecretResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_orange_key_admin_v1_admin_proto_init() }
func file_orange_key_admin_v1_admin_proto_init() {
	if File_orange_key_admin_v1_admin_proto != nil {
		return
	}
	file_orange_key_admin_v1_admin_proto_msgTypes[0].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[4].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[6].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[10].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[11].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[15].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[19].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[20].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[24].OneofWrappers = []any{}
	file_orange_key_admin_v1_admin_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_key_admin_v1_admin_proto_rawDesc), len(file_orange_key_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orange_key_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_orange_key_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_orange_key_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_orange_key_admin_v1_admin_proto = out.File
	file_orange_key_admin_v1_admin_proto_goTypes = nil
	file_orange_key_admin_v1_admin_proto_depIdxs = nil
}
