// admin.proto — EgressAdminService: Egress instance, identity, key-pair, and
// control-plane validation key management.
//
// A Workspace owns exactly one Egress. The Egress is the proxy instance
// responsible for request dispatch and policy enforcement.
//
// EgressIdentity is the X.509 certificate attesting workspace ownership.
// EgressKeyPair is the asymmetric key pair used for egress → control-plane auth.
// CPValidationKey is the control-plane public key distributed to egress instances.
//
// egress_id, identity_id, keypair_id, cpvalidation_key_id are server-assigned UUID7s.
//
// Authentication: every RPC requires AUTH_TYPE_API_KEY with scope "admin".
//
// Field numbers are stable and must not be reused once released.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/egress/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/transit/examples/orange/api/orange/egress/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EgressAdminServiceName is the fully-qualified name of the EgressAdminService service.
	EgressAdminServiceName = "orange.egress.admin.v1.EgressAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EgressAdminServiceCreateEgressProcedure is the fully-qualified name of the EgressAdminService's
	// CreateEgress RPC.
	EgressAdminServiceCreateEgressProcedure = "/orange.egress.admin.v1.EgressAdminService/CreateEgress"
	// EgressAdminServiceGetEgressProcedure is the fully-qualified name of the EgressAdminService's
	// GetEgress RPC.
	EgressAdminServiceGetEgressProcedure = "/orange.egress.admin.v1.EgressAdminService/GetEgress"
	// EgressAdminServiceUpdateEgressProcedure is the fully-qualified name of the EgressAdminService's
	// UpdateEgress RPC.
	EgressAdminServiceUpdateEgressProcedure = "/orange.egress.admin.v1.EgressAdminService/UpdateEgress"
	// EgressAdminServiceDeleteEgressProcedure is the fully-qualified name of the EgressAdminService's
	// DeleteEgress RPC.
	EgressAdminServiceDeleteEgressProcedure = "/orange.egress.admin.v1.EgressAdminService/DeleteEgress"
	// EgressAdminServiceIssueIdentityProcedure is the fully-qualified name of the EgressAdminService's
	// IssueIdentity RPC.
	EgressAdminServiceIssueIdentityProcedure = "/orange.egress.admin.v1.EgressAdminService/IssueIdentity"
	// EgressAdminServiceGetIdentityProcedure is the fully-qualified name of the EgressAdminService's
	// GetIdentity RPC.
	EgressAdminServiceGetIdentityProcedure = "/orange.egress.admin.v1.EgressAdminService/GetIdentity"
	// EgressAdminServiceListIdentitiesProcedure is the fully-qualified name of the EgressAdminService's
	// ListIdentities RPC.
	EgressAdminServiceListIdentitiesProcedure = "/orange.egress.admin.v1.EgressAdminService/ListIdentities"
	// EgressAdminServiceRevokeIdentityProcedure is the fully-qualified name of the EgressAdminService's
	// RevokeIdentity RPC.
	EgressAdminServiceRevokeIdentityProcedure = "/orange.egress.admin.v1.EgressAdminService/RevokeIdentity"
	// EgressAdminServiceRotateKeyPairProcedure is the fully-qualified name of the EgressAdminService's
	// RotateKeyPair RPC.
	EgressAdminServiceRotateKeyPairProcedure = "/orange.egress.admin.v1.EgressAdminService/RotateKeyPair"
	// EgressAdminServiceGetKeyPairProcedure is the fully-qualified name of the EgressAdminService's
	// GetKeyPair RPC.
	EgressAdminServiceGetKeyPairProcedure = "/orange.egress.admin.v1.EgressAdminService/GetKeyPair"
	// EgressAdminServiceListKeyPairsProcedure is the fully-qualified name of the EgressAdminService's
	// ListKeyPairs RPC.
	EgressAdminServiceListKeyPairsProcedure = "/orange.egress.admin.v1.EgressAdminService/ListKeyPairs"
	// EgressAdminServiceCreateCPValidationKeyProcedure is the fully-qualified name of the
	// EgressAdminService's CreateCPValidationKey RPC.
	EgressAdminServiceCreateCPValidationKeyProcedure = "/orange.egress.admin.v1.EgressAdminService/CreateCPValidationKey"
	// EgressAdminServiceGetCPValidationKeyProcedure is the fully-qualified name of the
	// EgressAdminService's GetCPValidationKey RPC.
	EgressAdminServiceGetCPValidationKeyProcedure = "/orange.egress.admin.v1.EgressAdminService/GetCPValidationKey"
	// EgressAdminServiceListCPValidationKeysProcedure is the fully-qualified name of the
	// EgressAdminService's ListCPValidationKeys RPC.
	EgressAdminServiceListCPValidationKeysProcedure = "/orange.egress.admin.v1.EgressAdminService/ListCPValidationKeys"
	// EgressAdminServiceDeactivateCPValidationKeyProcedure is the fully-qualified name of the
	// EgressAdminService's DeactivateCPValidationKey RPC.
	EgressAdminServiceDeactivateCPValidationKeyProcedure = "/orange.egress.admin.v1.EgressAdminService/DeactivateCPValidationKey"
)

// EgressAdminServiceClient is a client for the orange.egress.admin.v1.EgressAdminService service.
type EgressAdminServiceClient interface {
	CreateEgress(context.Context, *connect.Request[v1.CreateEgressRequest]) (*connect.Response[v1.CreateEgressResponse], error)
	GetEgress(context.Context, *connect.Request[v1.GetEgressRequest]) (*connect.Response[v1.GetEgressResponse], error)
	UpdateEgress(context.Context, *connect.Request[v1.UpdateEgressRequest]) (*connect.Response[v1.UpdateEgressResponse], error)
	DeleteEgress(context.Context, *connect.Request[v1.DeleteEgressRequest]) (*connect.Response[v1.DeleteEgressResponse], error)
	// IssueIdentity provisions a new X.509 identity certificate for an Egress.
	IssueIdentity(context.Context, *connect.Request[v1.IssueIdentityRequest]) (*connect.Response[v1.IssueIdentityResponse], error)
	// GetIdentity returns the identity record for an Egress.
	GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error)
	// ListIdentities lists all identity records for an Egress (active and expired).
	ListIdentities(context.Context, *connect.Request[v1.ListIdentitiesRequest]) (*connect.Response[v1.ListIdentitiesResponse], error)
	// RevokeIdentity deactivates an identity certificate.
	RevokeIdentity(context.Context, *connect.Request[v1.RevokeIdentityRequest]) (*connect.Response[v1.RevokeIdentityResponse], error)
	// RotateKeyPair generates a new asymmetric key pair for egress authentication.
	RotateKeyPair(context.Context, *connect.Request[v1.RotateKeyPairRequest]) (*connect.Response[v1.RotateKeyPairResponse], error)
	// GetKeyPair returns the active key pair record for an Egress (public key only).
	GetKeyPair(context.Context, *connect.Request[v1.GetKeyPairRequest]) (*connect.Response[v1.GetKeyPairResponse], error)
	// ListKeyPairs lists all key pair records for an Egress.
	ListKeyPairs(context.Context, *connect.Request[v1.ListKeyPairsRequest]) (*connect.Response[v1.ListKeyPairsResponse], error)
	// CreateCPValidationKey registers a control-plane public key for distribution.
	CreateCPValidationKey(context.Context, *connect.Request[v1.CreateCPValidationKeyRequest]) (*connect.Response[v1.CreateCPValidationKeyResponse], error)
	// GetCPValidationKey returns a control-plane validation key.
	GetCPValidationKey(context.Context, *connect.Request[v1.GetCPValidationKeyRequest]) (*connect.Response[v1.GetCPValidationKeyResponse], error)
	// ListCPValidationKeys lists all control-plane validation keys.
	ListCPValidationKeys(context.Context, *connect.Request[v1.ListCPValidationKeysRequest]) (*connect.Response[v1.ListCPValidationKeysResponse], error)
	// DeactivateCPValidationKey marks a control-plane key as inactive.
	DeactivateCPValidationKey(context.Context, *connect.Request[v1.DeactivateCPValidationKeyRequest]) (*connect.Response[v1.DeactivateCPValidationKeyResponse], error)
}

// NewEgressAdminServiceClient constructs a client for the orange.egress.admin.v1.EgressAdminService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEgressAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EgressAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	egressAdminServiceMethods := v1.File_orange_egress_admin_v1_admin_proto.Services().ByName("EgressAdminService").Methods()
	return &egressAdminServiceClient{
		createEgress: connect.NewClient[v1.CreateEgressRequest, v1.CreateEgressResponse](
			httpClient,
			baseURL+EgressAdminServiceCreateEgressProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("CreateEgress")),
			connect.WithClientOptions(opts...),
		),
		getEgress: connect.NewClient[v1.GetEgressRequest, v1.GetEgressResponse](
			httpClient,
			baseURL+EgressAdminServiceGetEgressProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("GetEgress")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateEgress: connect.NewClient[v1.UpdateEgressRequest, v1.UpdateEgressResponse](
			httpClient,
			baseURL+EgressAdminServiceUpdateEgressProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("UpdateEgress")),
			connect.WithClientOptions(opts...),
		),
		deleteEgress: connect.NewClient[v1.DeleteEgressRequest, v1.DeleteEgressResponse](
			httpClient,
			baseURL+EgressAdminServiceDeleteEgressProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("DeleteEgress")),
			connect.WithClientOptions(opts...),
		),
		issueIdentity: connect.NewClient[v1.IssueIdentityRequest, v1.IssueIdentityResponse](
			httpClient,
			baseURL+EgressAdminServiceIssueIdentityProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("IssueIdentity")),
			connect.WithClientOptions(opts...),
		),
		getIdentity: connect.NewClient[v1.GetIdentityRequest, v1.GetIdentityResponse](
			httpClient,
			baseURL+EgressAdminServiceGetIdentityProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("GetIdentity")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listIdentities: connect.NewClient[v1.ListIdentitiesRequest, v1.ListIdentitiesResponse](
			httpClient,
			baseURL+EgressAdminServiceListIdentitiesProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("ListIdentities")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		revokeIdentity: connect.NewClient[v1.RevokeIdentityRequest, v1.RevokeIdentityResponse](
			httpClient,
			baseURL+EgressAdminServiceRevokeIdentityProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("RevokeIdentity")),
			connect.WithClientOptions(opts...),
		),
		rotateKeyPair: connect.NewClient[v1.RotateKeyPairRequest, v1.RotateKeyPairResponse](
			httpClient,
			baseURL+EgressAdminServiceRotateKeyPairProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("RotateKeyPair")),
			connect.WithClientOptions(opts...),
		),
		getKeyPair: connect.NewClient[v1.GetKeyPairRequest, v1.GetKeyPairResponse](
			httpClient,
			baseURL+EgressAdminServiceGetKeyPairProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("GetKeyPair")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listKeyPairs: connect.NewClient[v1.ListKeyPairsRequest, v1.ListKeyPairsResponse](
			httpClient,
			baseURL+EgressAdminServiceListKeyPairsProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("ListKeyPairs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createCPValidationKey: connect.NewClient[v1.CreateCPValidationKeyRequest, v1.CreateCPValidationKeyResponse](
			httpClient,
			baseURL+EgressAdminServiceCreateCPValidationKeyProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("CreateCPValidationKey")),
			connect.WithClientOptions(opts...),
		),
		getCPValidationKey: connect.NewClient[v1.GetCPValidationKeyRequest, v1.GetCPValidationKeyResponse](
			httpClient,
			baseURL+EgressAdminServiceGetCPValidationKeyProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("GetCPValidationKey")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listCPValidationKeys: connect.NewClient[v1.ListCPValidationKeysRequest, v1.ListCPValidationKeysResponse](
			httpClient,
			baseURL+EgressAdminServiceListCPValidationKeysProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("ListCPValidationKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		deactivateCPValidationKey: connect.NewClient[v1.DeactivateCPValidationKeyRequest, v1.DeactivateCPValidationKeyResponse](
			httpClient,
			baseURL+EgressAdminServiceDeactivateCPValidationKeyProcedure,
			connect.WithSchema(egressAdminServiceMethods.ByName("DeactivateCPValidationKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// egressAdminServiceClient implements EgressAdminServiceClient.
type egressAdminServiceClient struct {
	createEgress              *connect.Client[v1.CreateEgressRequest, v1.CreateEgressResponse]
	getEgress                 *connect.Client[v1.GetEgressRequest, v1.GetEgressResponse]
	updateEgress              *connect.Client[v1.UpdateEgressRequest, v1.UpdateEgressResponse]
	deleteEgress              *connect.Client[v1.DeleteEgressRequest, v1.DeleteEgressResponse]
	issueIdentity             *connect.Client[v1.IssueIdentityRequest, v1.IssueIdentityResponse]
	getIdentity               *connect.Client[v1.GetIdentityRequest, v1.GetIdentityResponse]
	listIdentities            *connect.Client[v1.ListIdentitiesRequest, v1.ListIdentitiesResponse]
	revokeIdentity            *connect.Client[v1.RevokeIdentityRequest, v1.RevokeIdentityResponse]
	rotateKeyPair             *connect.Client[v1.RotateKeyPairRequest, v1.RotateKeyPairResponse]
	getKeyPair                *connect.Client[v1.GetKeyPairRequest, v1.GetKeyPairResponse]
	listKeyPairs              *connect.Client[v1.ListKeyPairsRequest, v1.ListKeyPairsResponse]
	createCPValidationKey     *connect.Client[v1.CreateCPValidationKeyRequest, v1.CreateCPValidationKeyResponse]
	getCPValidationKey        *connect.Client[v1.GetCPValidationKeyRequest, v1.GetCPValidationKeyResponse]
	listCPValidationKeys      *connect.Client[v1.ListCPValidationKeysRequest, v1.ListCPValidationKeysResponse]
	deactivateCPValidationKey *connect.Client[v1.DeactivateCPValidationKeyRequest, v1.DeactivateCPValidationKeyResponse]
}

// CreateEgress calls orange.egress.admin.v1.EgressAdminService.CreateEgress.
func (c *egressAdminServiceClient) CreateEgress(ctx context.Context, req *connect.Request[v1.CreateEgressRequest]) (*connect.Response[v1.CreateEgressResponse], error) {
	return c.createEgress.CallUnary(ctx, req)
}

// GetEgress calls orange.egress.admin.v1.EgressAdminService.GetEgress.
func (c *egressAdminServiceClient) GetEgress(ctx context.Context, req *connect.Request[v1.GetEgressRequest]) (*connect.Response[v1.GetEgressResponse], error) {
	return c.getEgress.CallUnary(ctx, req)
}

// UpdateEgress calls orange.egress.admin.v1.EgressAdminService.UpdateEgress.
func (c *egressAdminServiceClient) UpdateEgress(ctx context.Context, req *connect.Request[v1.UpdateEgressRequest]) (*connect.Response[v1.UpdateEgressResponse], error) {
	return c.updateEgress.CallUnary(ctx, req)
}

// DeleteEgress calls orange.egress.admin.v1.EgressAdminService.DeleteEgress.
func (c *egressAdminServiceClient) DeleteEgress(ctx context.Context, req *connect.Request[v1.DeleteEgressRequest]) (*connect.Response[v1.DeleteEgressResponse], error) {
	return c.deleteEgress.CallUnary(ctx, req)
}

// IssueIdentity calls orange.egress.admin.v1.EgressAdminService.IssueIdentity.
func (c *egressAdminServiceClient) IssueIdentity(ctx context.Context, req *connect.Request[v1.IssueIdentityRequest]) (*connect.Response[v1.IssueIdentityResponse], error) {
	return c.issueIdentity.CallUnary(ctx, req)
}

// GetIdentity calls orange.egress.admin.v1.EgressAdminService.GetIdentity.
func (c *egressAdminServiceClient) GetIdentity(ctx context.Context, req *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error) {
	return c.getIdentity.CallUnary(ctx, req)
}

// ListIdentities calls orange.egress.admin.v1.EgressAdminService.ListIdentities.
func (c *egressAdminServiceClient) ListIdentities(ctx context.Context, req *connect.Request[v1.ListIdentitiesRequest]) (*connect.Response[v1.ListIdentitiesResponse], error) {
	return c.listIdentities.CallUnary(ctx, req)
}

// RevokeIdentity calls orange.egress.admin.v1.EgressAdminService.RevokeIdentity.
func (c *egressAdminServiceClient) RevokeIdentity(ctx context.Context, req *connect.Request[v1.RevokeIdentityRequest]) (*connect.Response[v1.RevokeIdentityResponse], error) {
	return c.revokeIdentity.CallUnary(ctx, req)
}

// RotateKeyPair calls orange.egress.admin.v1.EgressAdminService.RotateKeyPair.
func (c *egressAdminServiceClient) RotateKeyPair(ctx context.Context, req *connect.Request[v1.RotateKeyPairRequest]) (*connect.Response[v1.RotateKeyPairResponse], error) {
	return c.rotateKeyPair.CallUnary(ctx, req)
}

// GetKeyPair calls orange.egress.admin.v1.EgressAdminService.GetKeyPair.
func (c *egressAdminServiceClient) GetKeyPair(ctx context.Context, req *connect.Request[v1.GetKeyPairRequest]) (*connect.Response[v1.GetKeyPairResponse], error) {
	return c.getKeyPair.CallUnary(ctx, req)
}

// ListKeyPairs calls orange.egress.admin.v1.EgressAdminService.ListKeyPairs.
func (c *egressAdminServiceClient) ListKeyPairs(ctx context.Context, req *connect.Request[v1.ListKeyPairsRequest]) (*connect.Response[v1.ListKeyPairsResponse], error) {
	return c.listKeyPairs.CallUnary(ctx, req)
}

// CreateCPValidationKey calls orange.egress.admin.v1.EgressAdminService.CreateCPValidationKey.
func (c *egressAdminServiceClient) CreateCPValidationKey(ctx context.Context, req *connect.Request[v1.CreateCPValidationKeyRequest]) (*connect.Response[v1.CreateCPValidationKeyResponse], error) {
	return c.createCPValidationKey.CallUnary(ctx, req)
}

// GetCPValidationKey calls orange.egress.admin.v1.EgressAdminService.GetCPValidationKey.
func (c *egressAdminServiceClient) GetCPValidationKey(ctx context.Context, req *connect.Request[v1.GetCPValidationKeyRequest]) (*connect.Response[v1.GetCPValidationKeyResponse], error) {
	return c.getCPValidationKey.CallUnary(ctx, req)
}

// ListCPValidationKeys calls orange.egress.admin.v1.EgressAdminService.ListCPValidationKeys.
func (c *egressAdminServiceClient) ListCPValidationKeys(ctx context.Context, req *connect.Request[v1.ListCPValidationKeysRequest]) (*connect.Response[v1.ListCPValidationKeysResponse], error) {
	return c.listCPValidationKeys.CallUnary(ctx, req)
}

// DeactivateCPValidationKey calls
// orange.egress.admin.v1.EgressAdminService.DeactivateCPValidationKey.
func (c *egressAdminServiceClient) DeactivateCPValidationKey(ctx context.Context, req *connect.Request[v1.DeactivateCPValidationKeyRequest]) (*connect.Response[v1.DeactivateCPValidationKeyResponse], error) {
	return c.deactivateCPValidationKey.CallUnary(ctx, req)
}

// EgressAdminServiceHandler is an implementation of the orange.egress.admin.v1.EgressAdminService
// service.
type EgressAdminServiceHandler interface {
	CreateEgress(context.Context, *connect.Request[v1.CreateEgressRequest]) (*connect.Response[v1.CreateEgressResponse], error)
	GetEgress(context.Context, *connect.Request[v1.GetEgressRequest]) (*connect.Response[v1.GetEgressResponse], error)
	UpdateEgress(context.Context, *connect.Request[v1.UpdateEgressRequest]) (*connect.Response[v1.UpdateEgressResponse], error)
	DeleteEgress(context.Context, *connect.Request[v1.DeleteEgressRequest]) (*connect.Response[v1.DeleteEgressResponse], error)
	// IssueIdentity provisions a new X.509 identity certificate for an Egress.
	IssueIdentity(context.Context, *connect.Request[v1.IssueIdentityRequest]) (*connect.Response[v1.IssueIdentityResponse], error)
	// GetIdentity returns the identity record for an Egress.
	GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error)
	// ListIdentities lists all identity records for an Egress (active and expired).
	ListIdentities(context.Context, *connect.Request[v1.ListIdentitiesRequest]) (*connect.Response[v1.ListIdentitiesResponse], error)
	// RevokeIdentity deactivates an identity certificate.
	RevokeIdentity(context.Context, *connect.Request[v1.RevokeIdentityRequest]) (*connect.Response[v1.RevokeIdentityResponse], error)
	// RotateKeyPair generates a new asymmetric key pair for egress authentication.
	RotateKeyPair(context.Context, *connect.Request[v1.RotateKeyPairRequest]) (*connect.Response[v1.RotateKeyPairResponse], error)
	// GetKeyPair returns the active key pair record for an Egress (public key only).
	GetKeyPair(context.Context, *connect.Request[v1.GetKeyPairRequest]) (*connect.Response[v1.GetKeyPairResponse], error)
	// ListKeyPairs lists all key pair records for an Egress.
	ListKeyPairs(context.Context, *connect.Request[v1.ListKeyPairsRequest]) (*connect.Response[v1.ListKeyPairsResponse], error)
	// CreateCPValidationKey registers a control-plane public key for distribution.
	CreateCPValidationKey(context.Context, *connect.Request[v1.CreateCPValidationKeyRequest]) (*connect.Response[v1.CreateCPValidationKeyResponse], error)
	// GetCPValidationKey returns a control-plane validation key.
	GetCPValidationKey(context.Context, *connect.Request[v1.GetCPValidationKeyRequest]) (*connect.Response[v1.GetCPValidationKeyResponse], error)
	// ListCPValidationKeys lists all control-plane validation keys.
	ListCPValidationKeys(context.Context, *connect.Request[v1.ListCPValidationKeysRequest]) (*connect.Response[v1.ListCPValidationKeysResponse], error)
	// DeactivateCPValidationKey marks a control-plane key as inactive.
	DeactivateCPValidationKey(context.Context, *connect.Request[v1.DeactivateCPValidationKeyRequest]) (*connect.Response[v1.DeactivateCPValidationKeyResponse], error)
}

// NewEgressAdminServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEgressAdminServiceHandler(svc EgressAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	egressAdminServiceMethods := v1.File_orange_egress_admin_v1_admin_proto.Services().ByName("EgressAdminService").Methods()
	egressAdminServiceCreateEgressHandler := connect.NewUnaryHandler(
		EgressAdminServiceCreateEgressProcedure,
		svc.CreateEgress,
		connect.WithSchema(egressAdminServiceMethods.ByName("CreateEgress")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceGetEgressHandler := connect.NewUnaryHandler(
		EgressAdminServiceGetEgressProcedure,
		svc.GetEgress,
		connect.WithSchema(egressAdminServiceMethods.ByName("GetEgress")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceUpdateEgressHandler := connect.NewUnaryHandler(
		EgressAdminServiceUpdateEgressProcedure,
		svc.UpdateEgress,
		connect.WithSchema(egressAdminServiceMethods.ByName("UpdateEgress")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceDeleteEgressHandler := connect.NewUnaryHandler(
		EgressAdminServiceDeleteEgressProcedure,
		svc.DeleteEgress,
		connect.WithSchema(egressAdminServiceMethods.ByName("DeleteEgress")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceIssueIdentityHandler := connect.NewUnaryHandler(
		EgressAdminServiceIssueIdentityProcedure,
		svc.IssueIdentity,
		connect.WithSchema(egressAdminServiceMethods.ByName("IssueIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceGetIdentityHandler := connect.NewUnaryHandler(
		EgressAdminServiceGetIdentityProcedure,
		svc.GetIdentity,
		connect.WithSchema(egressAdminServiceMethods.ByName("GetIdentity")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceListIdentitiesHandler := connect.NewUnaryHandler(
		EgressAdminServiceListIdentitiesProcedure,
		svc.ListIdentities,
		connect.WithSchema(egressAdminServiceMethods.ByName("ListIdentities")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceRevokeIdentityHandler := connect.NewUnaryHandler(
		EgressAdminServiceRevokeIdentityProcedure,
		svc.RevokeIdentity,
		connect.WithSchema(egressAdminServiceMethods.ByName("RevokeIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceRotateKeyPairHandler := connect.NewUnaryHandler(
		EgressAdminServiceRotateKeyPairProcedure,
		svc.RotateKeyPair,
		connect.WithSchema(egressAdminServiceMethods.ByName("RotateKeyPair")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceGetKeyPairHandler := connect.NewUnaryHandler(
		EgressAdminServiceGetKeyPairProcedure,
		svc.GetKeyPair,
		connect.WithSchema(egressAdminServiceMethods.ByName("GetKeyPair")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceListKeyPairsHandler := connect.NewUnaryHandler(
		EgressAdminServiceListKeyPairsProcedure,
		svc.ListKeyPairs,
		connect.WithSchema(egressAdminServiceMethods.ByName("ListKeyPairs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceCreateCPValidationKeyHandler := connect.NewUnaryHandler(
		EgressAdminServiceCreateCPValidationKeyProcedure,
		svc.CreateCPValidationKey,
		connect.WithSchema(egressAdminServiceMethods.ByName("CreateCPValidationKey")),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceGetCPValidationKeyHandler := connect.NewUnaryHandler(
		EgressAdminServiceGetCPValidationKeyProcedure,
		svc.GetCPValidationKey,
		connect.WithSchema(egressAdminServiceMethods.ByName("GetCPValidationKey")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceListCPValidationKeysHandler := connect.NewUnaryHandler(
		EgressAdminServiceListCPValidationKeysProcedure,
		svc.ListCPValidationKeys,
		connect.WithSchema(egressAdminServiceMethods.ByName("ListCPValidationKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	egressAdminServiceDeactivateCPValidationKeyHandler := connect.NewUnaryHandler(
		EgressAdminServiceDeactivateCPValidationKeyProcedure,
		svc.DeactivateCPValidationKey,
		connect.WithSchema(egressAdminServiceMethods.ByName("DeactivateCPValidationKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.egress.admin.v1.EgressAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EgressAdminServiceCreateEgressProcedure:
			egressAdminServiceCreateEgressHandler.ServeHTTP(w, r)
		case EgressAdminServiceGetEgressProcedure:
			egressAdminServiceGetEgressHandler.ServeHTTP(w, r)
		case EgressAdminServiceUpdateEgressProcedure:
			egressAdminServiceUpdateEgressHandler.ServeHTTP(w, r)
		case EgressAdminServiceDeleteEgressProcedure:
			egressAdminServiceDeleteEgressHandler.ServeHTTP(w, r)
		case EgressAdminServiceIssueIdentityProcedure:
			egressAdminServiceIssueIdentityHandler.ServeHTTP(w, r)
		case EgressAdminServiceGetIdentityProcedure:
			egressAdminServiceGetIdentityHandler.ServeHTTP(w, r)
		case EgressAdminServiceListIdentitiesProcedure:
			egressAdminServiceListIdentitiesHandler.ServeHTTP(w, r)
		case EgressAdminServiceRevokeIdentityProcedure:
			egressAdminServiceRevokeIdentityHandler.ServeHTTP(w, r)
		case EgressAdminServiceRotateKeyPairProcedure:
			egressAdminServiceRotateKeyPairHandler.ServeHTTP(w, r)
		case EgressAdminServiceGetKeyPairProcedure:
			egressAdminServiceGetKeyPairHandler.ServeHTTP(w, r)
		case EgressAdminServiceListKeyPairsProcedure:
			egressAdminServiceListKeyPairsHandler.ServeHTTP(w, r)
		case EgressAdminServiceCreateCPValidationKeyProcedure:
			egressAdminServiceCreateCPValidationKeyHandler.ServeHTTP(w, r)
		case EgressAdminServiceGetCPValidationKeyProcedure:
			egressAdminServiceGetCPValidationKeyHandler.ServeHTTP(w, r)
		case EgressAdminServiceListCPValidationKeysProcedure:
			egressAdminServiceListCPValidationKeysHandler.ServeHTTP(w, r)
		case EgressAdminServiceDeactivateCPValidationKeyProcedure:
			egressAdminServiceDeactivateCPValidationKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEgressAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEgressAdminServiceHandler struct{}

func (UnimplementedEgressAdminServiceHandler) CreateEgress(context.Context, *connect.Request[v1.CreateEgressRequest]) (*connect.Response[v1.CreateEgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.CreateEgress is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) GetEgress(context.Context, *connect.Request[v1.GetEgressRequest]) (*connect.Response[v1.GetEgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.GetEgress is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) UpdateEgress(context.Context, *connect.Request[v1.UpdateEgressRequest]) (*connect.Response[v1.UpdateEgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.UpdateEgress is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) DeleteEgress(context.Context, *connect.Request[v1.DeleteEgressRequest]) (*connect.Response[v1.DeleteEgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.DeleteEgress is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) IssueIdentity(context.Context, *connect.Request[v1.IssueIdentityRequest]) (*connect.Response[v1.IssueIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.IssueIdentity is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.GetIdentity is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) ListIdentities(context.Context, *connect.Request[v1.ListIdentitiesRequest]) (*connect.Response[v1.ListIdentitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.ListIdentities is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) RevokeIdentity(context.Context, *connect.Request[v1.RevokeIdentityRequest]) (*connect.Response[v1.RevokeIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.RevokeIdentity is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) RotateKeyPair(context.Context, *connect.Request[v1.RotateKeyPairRequest]) (*connect.Response[v1.RotateKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.RotateKeyPair is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) GetKeyPair(context.Context, *connect.Request[v1.GetKeyPairRequest]) (*connect.Response[v1.GetKeyPairResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.GetKeyPair is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) ListKeyPairs(context.Context, *connect.Request[v1.ListKeyPairsRequest]) (*connect.Response[v1.ListKeyPairsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.ListKeyPairs is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) CreateCPValidationKey(context.Context, *connect.Request[v1.CreateCPValidationKeyRequest]) (*connect.Response[v1.CreateCPValidationKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.CreateCPValidationKey is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) GetCPValidationKey(context.Context, *connect.Request[v1.GetCPValidationKeyRequest]) (*connect.Response[v1.GetCPValidationKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.GetCPValidationKey is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) ListCPValidationKeys(context.Context, *connect.Request[v1.ListCPValidationKeysRequest]) (*connect.Response[v1.ListCPValidationKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.ListCPValidationKeys is not implemented"))
}

func (UnimplementedEgressAdminServiceHandler) DeactivateCPValidationKey(context.Context, *connect.Request[v1.DeactivateCPValidationKeyRequest]) (*connect.Response[v1.DeactivateCPValidationKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.admin.v1.EgressAdminService.DeactivateCPValidationKey is not implemented"))
}
