// service.proto — EgressService: egress-proxy-facing (non-admin) endpoints.
//
// Called by running egress proxy instances, not by admin clients.
// Authentication is by egress keypair assertion (full auth in a future step);
// no API key required on these RPCs.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/egress/v1/service.proto

package egressv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/transit/examples/orange/api/orange/egress/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EgressServiceName is the fully-qualified name of the EgressService service.
	EgressServiceName = "orange.egress.v1.EgressService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EgressServiceHeartbeatProcedure is the fully-qualified name of the EgressService's Heartbeat RPC.
	EgressServiceHeartbeatProcedure = "/orange.egress.v1.EgressService/Heartbeat"
)

// EgressServiceClient is a client for the orange.egress.v1.EgressService service.
type EgressServiceClient interface {
	// Heartbeat is called periodically by the egress proxy to report liveness.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewEgressServiceClient constructs a client for the orange.egress.v1.EgressService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEgressServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EgressServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	egressServiceMethods := v1.File_orange_egress_v1_service_proto.Services().ByName("EgressService").Methods()
	return &egressServiceClient{
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+EgressServiceHeartbeatProcedure,
			connect.WithSchema(egressServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// egressServiceClient implements EgressServiceClient.
type egressServiceClient struct {
	heartbeat *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
}

// Heartbeat calls orange.egress.v1.EgressService.Heartbeat.
func (c *egressServiceClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// EgressServiceHandler is an implementation of the orange.egress.v1.EgressService service.
type EgressServiceHandler interface {
	// Heartbeat is called periodically by the egress proxy to report liveness.
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewEgressServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEgressServiceHandler(svc EgressServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	egressServiceMethods := v1.File_orange_egress_v1_service_proto.Services().ByName("EgressService").Methods()
	egressServiceHeartbeatHandler := connect.NewUnaryHandler(
		EgressServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(egressServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.egress.v1.EgressService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EgressServiceHeartbeatProcedure:
			egressServiceHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEgressServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEgressServiceHandler struct{}

func (UnimplementedEgressServiceHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.egress.v1.EgressService.Heartbeat is not implemented"))
}
